import type { CommercialFashionRule } from "../../types";

export const COMMERCIAL_FASHION_RULES: CommercialFashionRule[] = [
  {
    id: "would-buy",
    title: "Would Someone Buy This?",
    principle: "Commercial viability is non-negotiable — art without purchase intent fails the studio.",
    buyerQuestion: "Would someone buy this at full price without a discount?",
    passCriteria: "Clear value proposition, premium perception, wardrobe integration.",
    failCriteria: "Novelty only, unwearable statement, trend-dependent gimmick.",
    whenToUse: "Final export gate — every candidate.",
    whenNotToUse: "Never skip for 'creative exploration'.",
    signals: ["purchase-intent", "wardrobe-fit", "value"],
    antiPatterns: ["art-only", "unwearable", "gimmick"],
  },
  {
    id: "would-wear",
    title: "Would Someone Wear This?",
    principle: "Garment-scale wearability beats poster-scale impact.",
    buyerQuestion: "Would someone wear this weekly, not just photograph it once?",
    passCriteria: "Daily rotation potential, layering friendly, distance-readable.",
    failCriteria: "Costume piece, event-only, cringe in public context.",
    whenToUse: "Placement and density decisions.",
    whenNotToUse: "Never override for social-only appeal.",
    signals: ["daily-wear", "layering", "readability"],
    antiPatterns: ["costume", "one-photo", "cringe"],
  },
  {
    id: "would-share",
    title: "Would Someone Share This?",
    principle: "Shareability requires scroll-stop without sacrificing wearability.",
    buyerQuestion: "Would someone post a back-shot or flat-lay without embarrassment?",
    passCriteria: "Back placement, focal clarity, brand-appropriate aesthetic.",
    failCriteria: "Try-hard hype, meme energy, counterfeit vibes.",
    whenToUse: "Back print and campaign piece evaluation.",
    whenNotToUse: "Do not optimize share at expense of wear.",
    signals: ["back-shot", "flat-lay", "scroll-stop"],
    antiPatterns: ["meme", "try-hard", "embarrassing"],
  },
  {
    id: "feels-premium",
    title: "Does It Feel Premium?",
    principle: "Premium is felt before it is analyzed — void, tracking, craft.",
    buyerQuestion: "Does this feel like €55+ quality beside A-COLD-WALL*, Acne Studios, or Represent?",
    passCriteria: "Negative space, editorial type, production marks, restraint.",
    failCriteria: "Poster density, cheap tracking, clipart symbols.",
    whenToUse: "Every scoring dimension weights premium perception.",
    whenNotToUse: "Never trade premium for novelty.",
    signals: ["void", "craft", "restraint"],
    antiPatterns: ["poster", "clipart", "tight-type"],
  },
  {
    id: "feels-original",
    title: "Does It Feel Original?",
    principle: "Original within luxury streetwear grammar — not random, not derivative.",
    buyerQuestion: "Does this feel Milaene-specific, not borrowed from another house?",
    passCriteria: "Boundary symbolism, editorial type, calm luxury DNA.",
    failCriteria: "Supreme box, Bape camo energy, skull/wolf cliché.",
    whenToUse: "Originality gate before export.",
    whenNotToUse: "Never accept 'close enough' to competitor aesthetics.",
    signals: ["milaene-dna", "differentiated", "calm-luxury"],
    antiPatterns: ["derivative", "cliché", "competitor-copy"],
  },
  {
    id: "survives-premium-context",
    title: "Survives Beside Premium Brands?",
    principle: "The piece must hold its own on a rack beside €80–120 streetwear.",
    buyerQuestion: "Would this survive beside premium streetwear brands without looking cheaper?",
    passCriteria: "Composition richness, typography quality, graphic systems present.",
    failCriteria: "Text-only SVG, plain logo, no graphic craft.",
    whenToUse: "Export threshold — minimum Kittl-level composition.",
    whenNotToUse: "Never export plain typography-only artwork.",
    signals: ["composition-rich", "graphic-craft", "typography-quality"],
    antiPatterns: ["text-only", "plain-logo", "no-craft"],
  },
  {
    id: "milaene-price-test",
    title: "€55 Price Test",
    principle: "Milaene targets premium everyday luxury — the design must justify the price point.",
    buyerQuestion: "Would I pay €55 for this on an oversized tee?",
    passCriteria: "Premium perception + wearability + originality combined ≥ 90.",
    failCriteria: "Any single dimension below commercial floor.",
    whenToUse: "Creative thinking gate — all five questions must pass.",
    whenNotToUse: "Never waive for internal convenience.",
    signals: ["price-justified", "premium-stack"],
    antiPatterns: ["€25-perception", "fast-fashion-feel"],
  },
];

export const COMMERCIAL_BUYER_QUESTIONS = COMMERCIAL_FASHION_RULES.map((r) => r.buyerQuestion);

export function getCommercialRule(id: string): CommercialFashionRule | undefined {
  return COMMERCIAL_FASHION_RULES.find((r) => r.id === id);
}
