import type { GraphicSystemKnowledge } from "../../types";

export const GRAPHIC_SYSTEMS: GraphicSystemKnowledge[] = [
  {
    id: "line-systems",
    title: "Line Systems",
    principle: "Perimeter, axis, arc, and fragment lines create structure without figurative noise.",
    whenToUse: "Editorial backs, technical luxury, architect collection.",
    whenNotToUse: "Organic faith curves-only layouts, ultra-minimal floating marks.",
    whyItWorks: "Lines signal intention and production craft — Kittl-level composition scaffolding.",
    signals: ["perimeter", "axis", "arc", "fragment"],
    antiPatterns: ["random-lines", "decorative-only"],
  },
  {
    id: "boundary-systems",
    title: "Boundary Systems",
    principle: "Loops, frames, and perimeter enclosures define sacred space around type.",
    whenToUse: "Luxury badges, faith collection, capsule seals.",
    whenNotToUse: "Floating minimal, negative-space-dominant silent pieces.",
    whyItWorks: "Boundaries create premium containment — the eye reads 'designed' not 'placed'.",
    signals: ["loop", "frame", "perimeter", "enclosure"],
    antiPatterns: ["trapped-type", "heavy-box-logo"],
  },
  {
    id: "abstract-geometry",
    title: "Abstract Geometry",
    principle: "Non-figurative shapes carry meaning — arcs, shards, thresholds, not animals or skulls.",
    whenToUse: "Symbol language, architect/faith narratives, abstract streetwear.",
    whenNotToUse: "Literal storytelling, meme graphics, figurative hype.",
    whyItWorks: "Abstract geometry ages well and avoids trend cliché saturation.",
    signals: ["arc", "shard", "threshold", "geometric"],
    antiPatterns: ["skull", "animal", "wing"],
  },
  {
    id: "editorial-grids",
    title: "Editorial Grids",
    principle: "Thin structural grids imply magazine production quality and technical precision.",
    whenToUse: "Technical luxury, museum label, grid composition layouts.",
    whenNotToUse: "Distressed vintage, organic faith, soft editorial serif-only.",
    whyItWorks: "Grids whisper 'fashion production' not 'Canva template'.",
    signals: ["grid", "thin-lines", "editorial-structure"],
    antiPatterns: ["thick-grid", "visible-template"],
  },
  {
    id: "technical-markings",
    title: "Technical Markings",
    principle: "Registration ticks, notches, and production marks signal print-house literacy.",
    whenToUse: "Technical capsule, blueprint aesthetics, production-forward drops.",
    whenNotToUse: "Silent luxury, faith organic, minimal chest marks.",
    whyItWorks: "Markings create insider credibility with design-literate buyers.",
    signals: ["registration", "notch", "tick", "production"],
    antiPatterns: ["fake-blueprint-clutter", "meaningless-numbers"],
  },
  {
    id: "premium-labels",
    title: "Premium Labels",
    principle: "Heritage label blocks — framed metadata without copying any fashion house.",
    whenToUse: "Vintage label layouts, museum pieces, capsule numbering.",
    whenNotToUse: "Oversized center statements, floating minimal.",
    whyItWorks: "Label psychology triggers premium garment association.",
    signals: ["label-block", "heritage-frame", "metadata"],
    antiPatterns: ["fake-brand-label", "counterfeit-aesthetic"],
  },
  {
    id: "registration-marks",
    title: "Registration Marks",
    principle: "Corner crosshairs and alignment marks — subtle print-production authenticity.",
    whenToUse: "All premium templates at low opacity — corners only.",
    whenNotToUse: "Never dominant, never center-stage, never with fake coordinates.",
    whyItWorks: "Micro marks reward close inspection — luxury detail discovery.",
    signals: ["crosshair", "corner-mark", "alignment"],
    antiPatterns: ["center-crosshair", "loud-registration"],
  },
  {
    id: "coordinate-systems",
    title: "Coordinate Systems",
    principle: "Meaningful placement metadata only — capsule ID, season, not random numbers.",
    whenToUse: "When brief includes collection numbering or season narrative.",
    whenNotToUse: "Random lat/long, fake technical data, decoration-only coords.",
    whyItWorks: "Authentic metadata builds collection mythology.",
    signals: ["capsule-id", "season-code", "meaningful-meta"],
    antiPatterns: ["random-coords", "fake-gps"],
  },
  {
    id: "minimal-symbols",
    title: "Minimal Symbols",
    principle: "One dominant symbol system — geometric, organic, or architectural, never cluttered.",
    whenToUse: "Every layout — maximum 2–3 symbols at garment scale.",
    whenNotToUse: "Symbol gardens, competing geometry, figurative sets.",
    whyItWorks: "Restraint signals confidence — luxury never shouts with symbols.",
    signals: ["single-focal-symbol", "restraint"],
    antiPatterns: ["symbol-clutter", "competing-geometry"],
  },
  {
    id: "grain-systems",
    title: "Grain Systems",
    principle: "Controlled concrete grain at edges only — texture without destruction.",
    whenToUse: "Vintage label, editorial backs, material-forward briefs.",
    whenNotToUse: "Flat silent luxury, technical blueprint, minimal chest.",
    whyItWorks: "Subtle grain adds tactile premium perception in flat print.",
    signals: ["grain", "concrete", "edge-texture"],
    antiPatterns: ["full-surface-noise", "heavy-grunge"],
  },
  {
    id: "distressed-systems",
    title: "Distressed Systems",
    principle: "Edge fade and terminal distress only — never rave-era full destruction.",
    whenToUse: "Vintage capsule, heritage drops, controlled edge treatment.",
    whenNotToUse: "Silent collection, luxury badge, technical grid layouts.",
    whyItWorks: "Controlled distress reads 'worn luxury' not 'cheap thrift'.",
    signals: ["edge-fade", "terminal-distress", "controlled"],
    antiPatterns: ["full-destruction", "rave-grunge"],
  },
];

export function getGraphicSystem(id: GraphicSystemKnowledge["id"]): GraphicSystemKnowledge {
  const entry = GRAPHIC_SYSTEMS.find((s) => s.id === id);
  if (!entry) throw new Error(`Unknown graphic system: ${id}`);
  return entry;
}
