import type { DesignPatternTemplate } from "../../types";

/** 20 original premium design patterns — inspired by principles, not brand copies. */
export const DESIGN_PATTERN_CATALOG: DesignPatternTemplate[] = [
  {
    id: "silent-spine-statement",
    name: "Silent Spine Statement",
    description: "Vertical spine hero with perimeter arcs and 70% void — calm luxury back print.",
    layoutSystemId: "spine-layout",
    typographyHierarchy: ["hero-spine", "micro-horizontal"],
    graphicBalance: "Axis line + 2 arcs, symbols at spine intersection",
    negativeSpace: "70%",
    recommendedPrintSizeMm: { width: 280, height: 360 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["spine-back", "back"],
    difficulty: "advanced",
    commercialScore: 91,
    graphicSystems: ["line-systems", "boundary-systems", "registration-marks"],
    tags: ["silent", "spine", "luxury"],
  },
  {
    id: "editorial-back-campaign",
    name: "Editorial Back Campaign",
    description: "Upper-third hero with editorial grid and split type-graphic zones.",
    layoutSystemId: "editorial-layout",
    typographyHierarchy: ["hero-upper", "secondary-lower", "micro-credit"],
    graphicBalance: "Grid at 35% opacity, hero breaks frame",
    negativeSpace: "55%",
    recommendedPrintSizeMm: { width: 300, height: 380 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back", "upper-back"],
    difficulty: "intermediate",
    commercialScore: 89,
    graphicSystems: ["editorial-grids", "line-systems", "abstract-geometry"],
    tags: ["editorial", "campaign", "back"],
  },
  {
    id: "monument-center-back",
    name: "Monument Center Back",
    description: "Oversized centered statement with perimeter loop and boundary ticks.",
    layoutSystemId: "oversized-center",
    typographyHierarchy: ["hero-monument", "micro-below"],
    graphicBalance: "Perimeter frame at 65% hero scale, 2 boundary symbols",
    negativeSpace: "50%",
    recommendedPrintSizeMm: { width: 320, height: 400 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back", "upper-back"],
    difficulty: "intermediate",
    commercialScore: 92,
    graphicSystems: ["boundary-systems", "line-systems", "minimal-symbols"],
    tags: ["statement", "oversized", "viral"],
  },
  {
    id: "corner-chest-mark",
    name: "Corner Chest Mark",
    description: "Asymmetric upper-left chest with micro registration — daily rotation luxury.",
    layoutSystemId: "corner-composition",
    typographyHierarchy: ["hero-micro", "brand-whisper"],
    graphicBalance: "Single fragment line, one registration mark",
    negativeSpace: "75%",
    recommendedPrintSizeMm: { width: 80, height: 50 },
    garmentCompatibility: ["oversized-tee", "crewneck", "hoodie"],
    printAreas: ["left-chest", "front"],
    difficulty: "beginner",
    commercialScore: 88,
    graphicSystems: ["minimal-symbols", "registration-marks"],
    tags: ["chest", "minimal", "daily"],
  },
  {
    id: "heritage-badge-seal",
    name: "Heritage Badge Seal",
    description: "Luxury badge frame with heritage label block and corner diamonds.",
    layoutSystemId: "luxury-badge",
    typographyHierarchy: ["hero-inside-badge", "micro-below-frame"],
    graphicBalance: "Rounded rect frame, 2 corner marks, optional seal symbol",
    negativeSpace: "60%",
    recommendedPrintSizeMm: { width: 120, height: 100 },
    garmentCompatibility: ["oversized-tee", "hoodie", "crewneck"],
    printAreas: ["front", "back", "left-chest"],
    difficulty: "intermediate",
    commercialScore: 90,
    graphicSystems: ["premium-labels", "boundary-systems", "minimal-symbols"],
    tags: ["badge", "heritage", "seal"],
  },
  {
    id: "hem-metadata-band",
    name: "Hem Metadata Band",
    description: "Top-heavy hero with bottom label band for capsule storytelling.",
    layoutSystemId: "bottom-label",
    typographyHierarchy: ["hero-top", "micro-hem-band"],
    graphicBalance: "Top focal + thin horizontal rule above hem band",
    negativeSpace: "58%",
    recommendedPrintSizeMm: { width: 280, height: 340 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back"],
    difficulty: "intermediate",
    commercialScore: 87,
    graphicSystems: ["premium-labels", "line-systems", "coordinate-systems"],
    tags: ["metadata", "capsule", "label"],
  },
  {
    id: "mirror-upper-back",
    name: "Mirror Upper Back",
    description: "Top-heavy placement optimized for back-shot photography and mirror reads.",
    layoutSystemId: "top-heavy",
    typographyHierarchy: ["hero-upper", "secondary-mid"],
    graphicBalance: "Upper arcs, lower void, axis line",
    negativeSpace: "55%",
    recommendedPrintSizeMm: { width: 300, height: 360 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["upper-back", "back"],
    difficulty: "beginner",
    commercialScore: 90,
    graphicSystems: ["line-systems", "abstract-geometry"],
    tags: ["social", "upper-back", "photo"],
  },
  {
    id: "dynamic-diagonal-cut",
    name: "Dynamic Diagonal Cut",
    description: "Diagonal axis composition with shard geometry and tension void.",
    layoutSystemId: "diagonal-composition",
    typographyHierarchy: ["hero-diagonal", "micro-counter"],
    graphicBalance: "Diagonal line + 2 shard symbols, counter-diagonal void",
    negativeSpace: "52%",
    recommendedPrintSizeMm: { width: 290, height: 370 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back"],
    difficulty: "advanced",
    commercialScore: 86,
    graphicSystems: ["abstract-geometry", "line-systems"],
    tags: ["diagonal", "energy", "abstract"],
  },
  {
    id: "void-dominant-silent",
    name: "Void Dominant Silent",
    description: "Extreme negative space with single floating focal — quiet luxury.",
    layoutSystemId: "negative-space-layout",
    typographyHierarchy: ["hero-float"],
    graphicBalance: "One minimal symbol orbit, no frame",
    negativeSpace: "72%",
    recommendedPrintSizeMm: { width: 200, height: 260 },
    garmentCompatibility: ["oversized-tee", "crewneck", "hoodie"],
    printAreas: ["front", "back", "left-chest"],
    difficulty: "expert",
    commercialScore: 93,
    graphicSystems: ["minimal-symbols"],
    tags: ["silent", "void", "luxury"],
  },
  {
    id: "dual-zone-narrative",
    name: "Dual Zone Narrative",
    description: "Split type and symbol zones with editorial gutter separation.",
    layoutSystemId: "split-composition",
    typographyHierarchy: ["hero-type-zone", "graphic-zone-accent"],
    graphicBalance: "60/40 vertical split, divider line at 40% opacity",
    negativeSpace: "50%",
    recommendedPrintSizeMm: { width: 280, height: 360 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back"],
    difficulty: "advanced",
    commercialScore: 88,
    graphicSystems: ["abstract-geometry", "line-systems", "minimal-symbols"],
    tags: ["split", "narrative", "story"],
  },
  {
    id: "architect-blueprint",
    name: "Architect Blueprint",
    description: "Technical grid with registration marks and coordinate metadata.",
    layoutSystemId: "grid-composition",
    typographyHierarchy: ["hero-grid-break", "micro-coords"],
    graphicBalance: "Thin grid, corner marks, hero breaks intersection",
    negativeSpace: "55%",
    recommendedPrintSizeMm: { width: 300, height: 380 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back", "front"],
    difficulty: "advanced",
    commercialScore: 89,
    graphicSystems: ["editorial-grids", "technical-markings", "coordinate-systems", "registration-marks"],
    tags: ["architect", "technical", "grid"],
  },
  {
    id: "floating-ghost-type",
    name: "Floating Ghost Type",
    description: "Unframed hero floating in void with orbital micro elements.",
    layoutSystemId: "floating-composition",
    typographyHierarchy: ["hero-float", "micro-orbit"],
    graphicBalance: "No frame, 1 arc orbit, registration at corners only",
    negativeSpace: "68%",
    recommendedPrintSizeMm: { width: 260, height: 320 },
    garmentCompatibility: ["oversized-tee", "crewneck"],
    printAreas: ["front", "back"],
    difficulty: "intermediate",
    commercialScore: 91,
    graphicSystems: ["line-systems", "registration-marks", "minimal-symbols"],
    tags: ["floating", "ghost", "minimal"],
  },
  {
    id: "faith-perimeter-loop",
    name: "Faith Perimeter Loop",
    description: "Sacred geometry perimeter with spine axis and boundary symbolism.",
    layoutSystemId: "spine-layout",
    typographyHierarchy: ["hero-center", "micro-roman"],
    graphicBalance: "Perimeter loop, axis line, 2 boundary ticks",
    negativeSpace: "62%",
    recommendedPrintSizeMm: { width: 280, height: 360 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back", "spine-back"],
    difficulty: "advanced",
    commercialScore: 90,
    graphicSystems: ["boundary-systems", "abstract-geometry", "line-systems"],
    tags: ["faith", "perimeter", "sacred"],
  },
  {
    id: "vintage-label-heritage",
    name: "Vintage Label Heritage",
    description: "Heritage label block with controlled distress and grain at edges.",
    layoutSystemId: "luxury-badge",
    typographyHierarchy: ["serif-hero", "micro-heritage"],
    graphicBalance: "Label frame, grain overlay, coordinate mark",
    negativeSpace: "58%",
    recommendedPrintSizeMm: { width: 140, height: 110 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["front", "back"],
    difficulty: "intermediate",
    commercialScore: 87,
    graphicSystems: ["premium-labels", "grain-systems", "distressed-systems", "coordinate-systems"],
    tags: ["vintage", "heritage", "label"],
  },
  {
    id: "gallery-poster-back",
    name: "Gallery Poster Back",
    description: "Gallery editorial with cascading scale and edge-bleed geometry.",
    layoutSystemId: "editorial-layout",
    typographyHierarchy: ["hero-large", "secondary-cascade", "micro-gallery"],
    graphicBalance: "3 depth layers, edge fragment lines",
    negativeSpace: "48%",
    recommendedPrintSizeMm: { width: 320, height: 400 },
    garmentCompatibility: ["oversized-tee"],
    printAreas: ["back"],
    difficulty: "expert",
    commercialScore: 88,
    graphicSystems: ["abstract-geometry", "editorial-grids", "line-systems"],
    tags: ["gallery", "poster", "editorial"],
  },
  {
    id: "technical-luxury-mark",
    name: "Technical Luxury Mark",
    description: "Production-forward marks with blueprint grid and minimal symbol.",
    layoutSystemId: "grid-composition",
    typographyHierarchy: ["hero-technical", "micro-production"],
    graphicBalance: "Grid + registration + 1 geometric symbol",
    negativeSpace: "56%",
    recommendedPrintSizeMm: { width: 100, height: 80 },
    garmentCompatibility: ["oversized-tee", "hoodie", "crewneck"],
    printAreas: ["left-chest", "front"],
    difficulty: "intermediate",
    commercialScore: 89,
    graphicSystems: ["technical-markings", "editorial-grids", "minimal-symbols"],
    tags: ["technical", "production", "mark"],
  },
  {
    id: "season-capsule-hero",
    name: "Season Capsule Hero",
    description: "Campaign oversized center with capsule ID and season metadata.",
    layoutSystemId: "oversized-center",
    typographyHierarchy: ["hero-season", "micro-capsule-id"],
    graphicBalance: "Perimeter arcs, capsule coordinate, boundary symbols",
    negativeSpace: "52%",
    recommendedPrintSizeMm: { width: 300, height: 380 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back"],
    difficulty: "intermediate",
    commercialScore: 92,
    graphicSystems: ["coordinate-systems", "boundary-systems", "line-systems"],
    tags: ["capsule", "season", "drop"],
  },
  {
    id: "silent-left-chest",
    name: "Silent Left Chest",
    description: "Ultra-minimal corner chest with luxury tracking and zero frame.",
    layoutSystemId: "corner-composition",
    typographyHierarchy: ["hero-whisper"],
    graphicBalance: "No graphics or single 0.4mm fragment only",
    negativeSpace: "80%",
    recommendedPrintSizeMm: { width: 70, height: 45 },
    garmentCompatibility: ["oversized-tee", "crewneck", "hoodie", "long-sleeve"],
    printAreas: ["left-chest"],
    difficulty: "beginner",
    commercialScore: 94,
    graphicSystems: ["minimal-symbols"],
    tags: ["silent", "chest", "minimal"],
  },
  {
    id: "abstract-perimeter-system",
    name: "Abstract Perimeter System",
    description: "Concentric perimeter loops with abstract geometry and thin grid.",
    layoutSystemId: "floating-composition",
    typographyHierarchy: ["hero-center", "micro-perimeter"],
    graphicBalance: "Double perimeter, 4 arcs, thin grid at 25% opacity",
    negativeSpace: "54%",
    recommendedPrintSizeMm: { width: 290, height: 370 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back"],
    difficulty: "advanced",
    commercialScore: 90,
    graphicSystems: ["boundary-systems", "line-systems", "abstract-geometry", "editorial-grids"],
    tags: ["abstract", "perimeter", "system"],
  },
  {
    id: "luxury-editorial-stack",
    name: "Luxury Editorial Stack",
    description: "Stacked editorial type with serif hero, sans secondary, wide tracking.",
    layoutSystemId: "editorial-layout",
    typographyHierarchy: ["serif-hero-stack", "sans-secondary", "micro-brand"],
    graphicBalance: "Horizontal rules between stacks, 1 arc accent",
    negativeSpace: "57%",
    recommendedPrintSizeMm: { width: 280, height: 350 },
    garmentCompatibility: ["oversized-tee", "hoodie"],
    printAreas: ["back", "front"],
    difficulty: "intermediate",
    commercialScore: 91,
    graphicSystems: ["line-systems", "premium-labels"],
    tags: ["editorial", "stack", "luxury"],
  },
];

export const DESIGN_PATTERN_TARGET_COUNT = 200;

export function getPatternById(id: string): DesignPatternTemplate | undefined {
  return DESIGN_PATTERN_CATALOG.find((p) => p.id === id);
}
