import type { OrnamentSystemRecipe } from "@/lib/design/design-knowledge/ornament-language/types";
import { expandArchetype, lerp } from "@/lib/design/design-knowledge/shared/variant";

const FIT = ["oversized-front", "oversized-back", "center-chest", "sleeve", "corner"] as const;

function ornBase(p: Omit<OrnamentSystemRecipe, "id" | "meta">): Omit<OrnamentSystemRecipe, "id" | "meta"> {
  return p;
}

const ARCHETYPES: Parameters<typeof expandArchetype<OrnamentSystemRecipe>>[0][] = [
  { archetype: "Museum Captions", base: ornBase({ primary: ["roman-ids", "minimal-labels"], secondary: ["micro-dots"], belongs: ["caption", "edge"], never: ["never-center"], visualWeight: 0.28, density: "sparse", purpose: "museum indexing" }), variantCount: 10, name: () => "Museum Captions", tags: ["museum", "caption"], collections: ["museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.22, 0.35) }) },
  { archetype: "Editorial Rules", base: ornBase({ primary: ["rule-lines", "editorial-dividers"], secondary: ["vertical-rules"], belongs: ["flank", "edge"], never: ["never-center"], visualWeight: 0.35, density: "moderate", purpose: "editorial structure" }), variantCount: 10, name: () => "Editorial Rules", tags: ["editorial", "rules"], collections: ["editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, density: v % 2 === 0 ? "moderate" : "sparse" }) },
  { archetype: "Gallery Labels", base: ornBase({ primary: ["collection-numbers", "corner-marks"], secondary: ["minimal-labels"], belongs: ["caption", "edge"], never: ["never-center"], visualWeight: 0.32, density: "sparse", purpose: "gallery identification" }), variantCount: 10, name: () => "Gallery Labels", tags: ["gallery", "label"], collections: ["editorial", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.28, 0.38) }) },
  { archetype: "Micro Dots", base: ornBase({ primary: ["micro-dots", "micro-lines"], secondary: ["registration-marks"], belongs: ["micro", "edge"], never: ["never-center"], visualWeight: 0.18, density: "sparse", purpose: "micro detail" }), variantCount: 10, name: () => "Micro Dots", tags: ["micro", "dots"], collections: ["silent", "capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.14, 0.24) }) },
  { archetype: "Alignment Marks", base: ornBase({ primary: ["registration-marks", "alignment-guides"], secondary: ["corner-marks"], belongs: ["edge", "frame"], never: ["never-center"], visualWeight: 0.22, density: "sparse", purpose: "production alignment" }), variantCount: 10, name: () => "Alignment Marks", tags: ["alignment", "marks"], collections: ["architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, density: "sparse" }) },
  { archetype: "Production Stamps", base: ornBase({ primary: ["tiny-capsules", "minimal-labels"], secondary: ["roman-ids"], belongs: ["stamp", "caption"], never: ["never-center"], visualWeight: 0.25, density: "sparse", purpose: "production metadata" }), variantCount: 10, name: () => "Production Stamps", tags: ["production", "stamp"], collections: ["capsule", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.2, 0.3) }) },
  { archetype: "Serial IDs", base: ornBase({ primary: ["collection-numbers", "roman-ids"], secondary: ["micro-lines"], belongs: ["caption", "edge"], never: ["never-center"], visualWeight: 0.26, density: "sparse", purpose: "serial identification" }), variantCount: 10, name: () => "Serial IDs", tags: ["serial", "id"], collections: ["museum", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, primary: ["collection-numbers", "roman-ids"] }) },
  { archetype: "Measurement Systems", base: ornBase({ primary: ["coordinates", "rule-lines"], secondary: ["registration-marks"], belongs: ["edge", "flank"], never: ["never-center"], visualWeight: 0.3, density: "moderate", purpose: "dimensional reference" }), variantCount: 10, name: () => "Measurement Systems", tags: ["measurement", "coordinates"], collections: ["architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.25, 0.35) }) },
  { archetype: "Capsule Metadata", base: ornBase({ primary: ["tiny-capsules", "collection-numbers"], secondary: ["micro-dots"], belongs: ["stamp", "caption"], never: ["never-center"], visualWeight: 0.24, density: "sparse", purpose: "capsule identity" }), variantCount: 10, name: () => "Capsule Metadata", tags: ["capsule", "metadata"], collections: ["capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, density: "sparse" }) },
  { archetype: "Luxury Borders", base: ornBase({ primary: ["luxury-borders", "corner-marks"], secondary: ["flank-strikes"], belongs: ["frame", "edge"], never: ["never-center"], visualWeight: 0.38, density: "moderate", purpose: "luxury framing" }), variantCount: 10, name: () => "Luxury Borders", tags: ["luxury", "border"], collections: ["editorial", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.32, 0.45) }) },
  { archetype: "Flank Strikes", base: ornBase({ primary: ["flank-strikes", "vertical-rules"], secondary: ["rule-lines"], belongs: ["flank"], never: ["never-center"], visualWeight: 0.34, density: "moderate", purpose: "lateral tension" }), variantCount: 10, name: () => "Flank Strikes", tags: ["flank", "strikes"], collections: ["editorial", "architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, belongs: ["flank", "edge"] }) },
  { archetype: "Vertical Rules", base: ornBase({ primary: ["vertical-rules", "editorial-dividers"], secondary: ["micro-lines"], belongs: ["flank", "edge"], never: ["never-center"], visualWeight: 0.3, density: "moderate", purpose: "vertical rhythm" }), variantCount: 10, name: () => "Vertical Rules", tags: ["vertical", "rules"], collections: ["faith", "editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, density: v % 3 === 0 ? "dense" : "moderate" }) },
  { archetype: "Corner Marks", base: ornBase({ primary: ["corner-marks", "registration-marks"], secondary: ["micro-dots"], belongs: ["edge", "frame"], never: ["never-center"], visualWeight: 0.2, density: "sparse", purpose: "corner registration" }), variantCount: 10, name: () => "Corner Marks", tags: ["corner", "marks"], collections: ["architect", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.16, 0.26) }) },
  { archetype: "Faith Ornaments", base: ornBase({ primary: ["roman-ids", "vertical-rules"], secondary: ["micro-lines"], belongs: ["flank", "caption"], never: ["never-center"], visualWeight: 0.28, density: "sparse", purpose: "faith editorial" }), variantCount: 10, name: () => "Faith Ornaments", tags: ["faith", "ornament"], collections: ["faith"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, belongs: ["flank", "caption", "edge"] }) },
  { archetype: "Silent Accents", base: ornBase({ primary: ["micro-dots", "roman-ids"], secondary: ["minimal-labels"], belongs: ["micro", "caption"], never: ["never-center"], visualWeight: 0.16, density: "sparse", purpose: "silent luxury detail" }), variantCount: 10, name: () => "Silent Accents", tags: ["silent", "micro"], collections: ["silent"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.12, 0.2) }) },
  { archetype: "Campaign Stamps", base: ornBase({ primary: ["collection-numbers", "tiny-capsules", "flank-strikes"], secondary: ["editorial-dividers"], belongs: ["stamp", "flank", "caption"], never: ["never-center"], visualWeight: 0.36, density: "moderate", purpose: "campaign identity" }), variantCount: 10, name: () => "Campaign Stamps", tags: ["campaign", "stamp"], collections: ["editorial", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, density: "moderate" }) },
  { archetype: "Editorial Dividers", base: ornBase({ primary: ["editorial-dividers", "rule-lines"], secondary: ["micro-lines"], belongs: ["edge", "flank"], never: ["never-center"], visualWeight: 0.32, density: "moderate", purpose: "section division" }), variantCount: 10, name: () => "Editorial Dividers", tags: ["divider", "editorial"], collections: ["editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.28, 0.38) }) },
  { archetype: "Coordinate Field", base: ornBase({ primary: ["coordinates", "alignment-guides"], secondary: ["registration-marks"], belongs: ["edge"], never: ["never-center"], visualWeight: 0.24, density: "sparse", purpose: "spatial reference" }), variantCount: 10, name: () => "Coordinate Field", tags: ["coordinates", "field"], collections: ["architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, never: ["never-center"] }) },
  { archetype: "Season Index", base: ornBase({ primary: ["collection-numbers", "roman-ids", "minimal-labels"], secondary: ["micro-dots"], belongs: ["caption", "stamp"], never: ["never-center"], visualWeight: 0.3, density: "sparse", purpose: "season indexing" }), variantCount: 10, name: () => "Season Index", tags: ["season", "index"], collections: ["season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, visualWeight: lerp(s, v, 0.26, 0.36) }) },
  { archetype: "Architect Registration", base: ornBase({ primary: ["registration-marks", "coordinates", "corner-marks"], secondary: ["rule-lines"], belongs: ["edge", "frame"], never: ["never-center"], visualWeight: 0.28, density: "moderate", purpose: "architectural registration" }), variantCount: 10, name: () => "Architect Registration", tags: ["architect", "registration"], collections: ["architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, density: v % 2 === 0 ? "moderate" : "sparse" }) },
];

export const ORNAMENT_ARCHETYPE_COUNT = ARCHETYPES.length;
export const ORNAMENT_VARIANTS_PER_ARCHETYPE = 10;
export const ORNAMENT_RECIPE_TARGET = ORNAMENT_ARCHETYPE_COUNT * ORNAMENT_VARIANTS_PER_ARCHETYPE;

export function buildAllOrnamentSystems(seed = 0): OrnamentSystemRecipe[] {
  return ARCHETYPES.flatMap((a) => expandArchetype<OrnamentSystemRecipe>(a, seed));
}
