import type {
  DesignStyleId,
  EffectId,
  HierarchyPreference,
  LayoutId,
  OrnamentId,
  SymbolId,
  TemplateDefinition,
  TemplateId,
  TypographySystemId,
} from "@/lib/design/design-library/types";

function tpl(
  id: TemplateId,
  name: string,
  styleId: DesignStyleId,
  layoutId: LayoutId,
  typographySystemId: TypographySystemId,
  primarySymbol: SymbolId,
  secondarySymbols: SymbolId[],
  ornaments: OrnamentId[],
  effects: EffectId[],
  hierarchy: HierarchyPreference,
): TemplateDefinition {
  return {
    id,
    name,
    styleId,
    layoutId,
    typographySystemId,
    primarySymbol,
    secondarySymbols,
    ornaments,
    effects,
    hierarchy,
  };
}

export const TEMPLATE_REGISTRY: Record<TemplateId, TemplateDefinition> = {
  "luxury-wordmark": tpl(
    "luxury-wordmark",
    "Luxury Wordmark",
    "minimal-luxury",
    "center-chest",
    "condensed",
    "interrupted-arc",
    ["halo"],
    ["rule-lines", "roman-ids", "tiny-capsules", "micro-lines"],
    ["outline", "filled"],
    "type-first",
  ),
  "editorial-poster": tpl(
    "editorial-poster",
    "Editorial Poster",
    "editorial-fashion",
    "oversized-front",
    "editorial-serif",
    "frame",
    ["architectural-line"],
    ["editorial-dividers", "rule-lines", "collection-numbers", "vertical-rules"],
    ["outline", "halftone"],
    "type-first",
  ),
  "faith-collection": tpl(
    "faith-collection",
    "Faith Collection",
    "faith",
    "symbol-above-type",
    "luxury-serif",
    "sacred-geometry",
    ["cross", "halo"],
    ["roman-ids", "minimal-labels", "rule-lines"],
    ["outline", "embroidery"],
    "geometry-first",
  ),
  "minimal-emblem": tpl(
    "minimal-emblem",
    "Minimal Emblem",
    "silent-luxury",
    "micro-chest",
    "condensed",
    "interrupted-arc",
    ["missing-center-void"],
    ["micro-dots", "roman-ids", "alignment-guides", "micro-lines"],
    ["outline", "fade"],
    "geometry-first",
  ),
  "technical-blueprint": tpl(
    "technical-blueprint",
    "Technical Blueprint",
    "technical-streetwear",
    "vertical-print",
    "grotesk",
    "grid",
    ["compass", "directional-marker"],
    ["coordinates", "registration-marks", "alignment-guides", "rule-lines"],
    ["outline", "screen-print-noise"],
    "balanced",
  ),
  "gallery-composition": tpl(
    "gallery-composition",
    "Gallery Composition",
    "vintage-washed",
    "gallery-layout",
    "extended",
    "broken-circle",
    ["split-circle", "orbit"],
    ["collection-numbers", "coordinates", "editorial-dividers"],
    ["vintage-distress", "washed"],
    "type-first",
  ),
  "silent-collection": tpl(
    "silent-collection",
    "Silent Collection",
    "silent-luxury",
    "floating-composition",
    "luxury-serif",
    "halo",
    ["missing-center-void"],
    ["micro-dots", "tiny-capsules", "roman-ids"],
    ["outline", "fade"],
    "geometry-first",
  ),
  "micro-graphic": tpl(
    "micro-graphic",
    "Micro Graphic",
    "japanese-minimal",
    "micro-chest",
    "modern-sans",
    "half-circle",
    ["minimal-eye"],
    ["micro-dots", "alignment-guides", "rule-lines"],
    ["outline", "filled"],
    "geometry-first",
  ),
  "oversized-graphic": tpl(
    "oversized-graphic",
    "Oversized Graphic",
    "editorial-fashion",
    "oversized-front",
    "extended",
    "architectural-line",
    ["frame"],
    ["editorial-dividers", "vertical-rules", "collection-numbers", "rule-lines"],
    ["outline", "heavy-ink"],
    "type-first",
  ),
  "monochrome-symbol": tpl(
    "monochrome-symbol",
    "Monochrome Symbol",
    "monochrome-luxury",
    "symbol-above-type",
    "luxury-serif",
    "diamond",
    ["interrupted-arc", "frame"],
    ["luxury-borders", "roman-ids", "tiny-capsules"],
    ["outline", "fade"],
    "geometry-first",
  ),
};

export const ALL_TEMPLATE_IDS = Object.keys(TEMPLATE_REGISTRY) as TemplateId[];

export function getTemplate(id: TemplateId): TemplateDefinition {
  return TEMPLATE_REGISTRY[id] ?? TEMPLATE_REGISTRY["luxury-wordmark"];
}
