import type { SymbolSystemRecipe } from "@/lib/design/design-knowledge/symbol-language/types";
import { expandArchetype, lerp } from "@/lib/design/design-knowledge/shared/variant";

const FIT = ["oversized-front", "oversized-back", "center-chest", "sleeve", "corner"] as const;

function symBase(p: Omit<SymbolSystemRecipe, "id" | "meta">): Omit<SymbolSystemRecipe, "id" | "meta"> {
  return p;
}

const ARCHETYPES: Parameters<typeof expandArchetype<SymbolSystemRecipe>>[0][] = [
  { archetype: "Architectural Frame", base: symBase({ primary: "frame", secondary: "architectural-line", nested: ["broken-circle"], priority: "dominant", depth: "midground", interaction: "frames-type", overlap: 0.35, masking: false, restraint: 0.55, relationships: ["frame-contains-type", "line-extends-frame"] }), variantCount: 10, name: () => "Architectural Frame", tags: ["frame", "architectural"], collections: ["architect", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, overlap: lerp(s, v, 0.28, 0.45) }) },
  { archetype: "Broken Halo", base: symBase({ primary: "halo", secondary: "broken-circle", nested: ["interrupted-arc"], priority: "dominant", depth: "background", interaction: "behind-type", overlap: 0.42, masking: true, restraint: 0.62, relationships: ["halo-frames-focal", "arc-breaks-circle"] }), variantCount: 10, name: () => "Broken Halo", tags: ["halo", "circle"], collections: ["editorial", "faith"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, masking: v % 2 === 0 }) },
  { archetype: "Dual Arc", base: symBase({ primary: "interrupted-arc", secondary: "orbit", nested: ["broken-circle"], priority: "secondary", depth: "midground", interaction: "overlaps-type", overlap: 0.48, masking: false, restraint: 0.58, relationships: ["dual-arc-tension", "orbit-rotation"] }), variantCount: 10, name: () => "Dual Arc", tags: ["arc", "orbit"], collections: ["editorial", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, restraint: lerp(s, v, 0.5, 0.68) }) },
  { archetype: "Negative Circle", base: symBase({ primary: "missing-center-void", secondary: "broken-circle", nested: ["half-circle"], priority: "dominant", depth: "midground", interaction: "masks-type", overlap: 0.38, masking: true, restraint: 0.7, relationships: ["void-defines-center", "circle-frames-void"] }), variantCount: 10, name: () => "Negative Circle", tags: ["void", "circle"], collections: ["silent", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, restraint: lerp(s, v, 0.62, 0.78) }) },
  { archetype: "Directional Markers", base: symBase({ primary: "directional-marker", secondary: "architectural-line", nested: ["minimal-star"], priority: "accent", depth: "foreground", interaction: "independent", overlap: 0.22, masking: false, restraint: 0.75, relationships: ["marker-points-flow", "line-directs-eye"] }), variantCount: 10, name: () => "Directional Markers", tags: ["directional", "marker"], collections: ["editorial", "architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, overlap: lerp(s, v, 0.15, 0.3) }) },
  { archetype: "Cross Systems", base: symBase({ primary: "cross", secondary: "sacred-geometry", nested: ["diamond"], priority: "dominant", depth: "midground", interaction: "frames-type", overlap: 0.4, masking: false, restraint: 0.5, relationships: ["cross-centers-composition", "geometry-radiates"] }), variantCount: 10, name: () => "Cross Systems", tags: ["cross", "faith"], collections: ["faith"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, nested: v % 2 === 0 ? ["diamond"] : ["minimal-star"] }) },
  { archetype: "Coordinate Systems", base: symBase({ primary: "compass", secondary: "grid", nested: ["directional-marker"], priority: "supporting", depth: "background", interaction: "independent", overlap: 0.25, masking: false, restraint: 0.65, relationships: ["grid-anchors-space", "compass-orients"] }), variantCount: 10, name: () => "Coordinate Systems", tags: ["coordinates", "grid"], collections: ["architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, depth: "background" }) },
  { archetype: "Diamond Systems", base: symBase({ primary: "diamond", secondary: "minimal-star", nested: ["frame"], priority: "secondary", depth: "midground", interaction: "overlaps-type", overlap: 0.35, masking: false, restraint: 0.6, relationships: ["diamond-centers-accent", "star-flanks"] }), variantCount: 10, name: () => "Diamond Systems", tags: ["diamond", "accent"], collections: ["museum", "capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, priority: v % 3 === 0 ? "dominant" : "secondary" }) },
  { archetype: "Minimal Construction", base: symBase({ primary: "architectural-line", secondary: "frame", nested: ["broken-circle"], priority: "supporting", depth: "background", interaction: "behind-type", overlap: 0.3, masking: false, restraint: 0.8, relationships: ["line-defines-structure", "minimal-restraint"] }), variantCount: 10, name: () => "Minimal Construction", tags: ["minimal", "line"], collections: ["silent", "capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, restraint: lerp(s, v, 0.72, 0.88) }) },
  { archetype: "Gallery Marks", base: symBase({ primary: "broken-circle", secondary: "orbit", nested: ["interrupted-arc", "frame"], priority: "dominant", depth: "midground", interaction: "frames-type", overlap: 0.45, masking: false, restraint: 0.52, relationships: ["circle-gallery-frame", "orbit-gallery-orbit"] }), variantCount: 10, name: () => "Gallery Marks", tags: ["gallery", "poster"], collections: ["editorial", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, overlap: lerp(s, v, 0.38, 0.55) }) },
  { archetype: "Editorial Markers", base: symBase({ primary: "interrupted-arc", secondary: "directional-marker", nested: ["broken-circle"], priority: "secondary", depth: "foreground", interaction: "overlaps-type", overlap: 0.5, masking: false, restraint: 0.55, relationships: ["arc-editorial-break", "marker-flow"] }), variantCount: 10, name: () => "Editorial Markers", tags: ["editorial", "marker"], collections: ["editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, interaction: "overlaps-type" }) },
  { archetype: "Capsule Systems", base: symBase({ primary: "missing-center-void", secondary: "diamond", nested: ["minimal-star"], priority: "dominant", depth: "midground", interaction: "masks-type", overlap: 0.32, masking: true, restraint: 0.72, relationships: ["void-capsule-identity", "diamond-capsule-mark"] }), variantCount: 10, name: () => "Capsule Systems", tags: ["capsule", "void"], collections: ["capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, masking: true }) },
  { archetype: "Sacred Geometry", base: symBase({ primary: "sacred-geometry", secondary: "cross", nested: ["halo", "diamond"], priority: "dominant", depth: "midground", interaction: "frames-type", overlap: 0.42, masking: false, restraint: 0.48, relationships: ["geometry-sacred-center", "cross-vertical-axis"] }), variantCount: 10, name: () => "Sacred Geometry", tags: ["sacred", "faith"], collections: ["faith"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, nested: ["halo", "cross"] }) },
  { archetype: "Split Circle", base: symBase({ primary: "split-circle", secondary: "half-circle", nested: ["interrupted-arc"], priority: "secondary", depth: "midground", interaction: "overlaps-type", overlap: 0.44, masking: false, restraint: 0.58, relationships: ["split-tension", "half-completion"] }), variantCount: 10, name: () => "Split Circle", tags: ["split", "circle"], collections: ["editorial", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, overlap: lerp(s, v, 0.38, 0.52) }) },
  { archetype: "Orbit System", base: symBase({ primary: "orbit", secondary: "broken-circle", nested: ["directional-marker"], priority: "secondary", depth: "background", interaction: "behind-type", overlap: 0.36, masking: false, restraint: 0.64, relationships: ["orbit-rotation", "circle-orbit-path"] }), variantCount: 10, name: () => "Orbit System", tags: ["orbit", "rotation"], collections: ["season", "editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, depth: v % 2 === 0 ? "background" : "midground" }) },
  { archetype: "Eye System", base: symBase({ primary: "minimal-eye", secondary: "halo", nested: ["broken-circle"], priority: "accent", depth: "foreground", interaction: "independent", overlap: 0.28, masking: false, restraint: 0.68, relationships: ["eye-focal-watch", "halo-eye-frame"] }), variantCount: 10, name: () => "Eye System", tags: ["eye", "watch"], collections: ["capsule", "editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, priority: "accent" }) },
  { archetype: "Grid Foundation", base: symBase({ primary: "grid", secondary: "architectural-line", nested: ["compass"], priority: "supporting", depth: "background", interaction: "behind-type", overlap: 0.2, masking: false, restraint: 0.7, relationships: ["grid-underlay", "line-grid-align"] }), variantCount: 10, name: () => "Grid Foundation", tags: ["grid", "technical"], collections: ["architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, restraint: lerp(s, v, 0.65, 0.82) }) },
  { archetype: "Frame Nest", base: symBase({ primary: "frame", secondary: "missing-center-void", nested: ["broken-circle", "interrupted-arc"], priority: "dominant", depth: "midground", interaction: "frames-type", overlap: 0.4, masking: true, restraint: 0.54, relationships: ["frame-outer", "void-inner", "arc-breaks"] }), variantCount: 10, name: () => "Frame Nest", tags: ["frame", "nest"], collections: ["architect", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, masking: v % 2 === 0 }) },
  { archetype: "Halo Restraint", base: symBase({ primary: "halo", secondary: "minimal-star", nested: ["diamond"], priority: "secondary", depth: "background", interaction: "behind-type", overlap: 0.3, masking: false, restraint: 0.78, relationships: ["halo-soft-boundary", "star-micro-accent"] }), variantCount: 10, name: () => "Halo Restraint", tags: ["halo", "restraint"], collections: ["silent", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, restraint: lerp(s, v, 0.72, 0.85) }) },
  { archetype: "Campaign Symbol", base: symBase({ primary: "broken-circle", secondary: "frame", nested: ["orbit", "directional-marker"], priority: "dominant", depth: "midground", interaction: "overlaps-type", overlap: 0.52, masking: false, restraint: 0.45, relationships: ["circle-campaign-hero", "frame-campaign-structure"] }), variantCount: 10, name: () => "Campaign Symbol", tags: ["campaign", "bold"], collections: ["editorial", "season"], garmentFit: ["oversized-front", "oversized-back"], mutate: (b, v, s) => ({ ...b, overlap: lerp(s, v, 0.45, 0.58), restraint: lerp(s, v + 1, 0.4, 0.52) }) },
];

export const SYMBOL_ARCHETYPE_COUNT = ARCHETYPES.length;
export const SYMBOL_VARIANTS_PER_ARCHETYPE = 10;
export const SYMBOL_RECIPE_TARGET = SYMBOL_ARCHETYPE_COUNT * SYMBOL_VARIANTS_PER_ARCHETYPE;

export function buildAllSymbolSystems(seed = 0): SymbolSystemRecipe[] {
  return ARCHETYPES.flatMap((a) => expandArchetype<SymbolSystemRecipe>(a, seed));
}
