import type { DesignStyleDefinition, DesignStyleId } from "@/lib/design/design-library/types";

const BASE: Omit<
  DesignStyleDefinition,
  "id" | "name" | "typographyPreference" | "preferredLayouts" | "preferredSymbols" | "preferredOrnaments" | "allowedEffects"
> = {
  spacing: { marginRatio: 0.08, safeZoneRatio: 0.92, elementGap: 12, baselineGrid: 4 },
  strokeHairline: 0.35,
  strokeThin: 0.6,
  strokeRegular: 1,
  trackingTight: 0.12,
  trackingNormal: 0.28,
  trackingWide: 0.48,
  headlineScale: 1,
  geometryScale: 1,
  negativeSpace: 0.28,
  visualRhythm: 1,
  alignment: "center",
  hierarchy: "balanced",
  preferredPrintScale: "standard",
};

function defineStyle(
  id: DesignStyleId,
  name: string,
  fields: Pick<
    DesignStyleDefinition,
    "typographyPreference" | "preferredLayouts" | "preferredSymbols" | "preferredOrnaments" | "allowedEffects"
  > &
    Partial<DesignStyleDefinition>,
): DesignStyleDefinition {
  return { ...BASE, id, name, ...fields };
}

export const STYLE_REGISTRY: Record<DesignStyleId, DesignStyleDefinition> = {
  "minimal-luxury": defineStyle("minimal-luxury", "Minimal Luxury", {
    typographyPreference: ["modern-sans", "condensed"],
    spacing: { ...BASE.spacing, elementGap: 16 },
    negativeSpace: 0.38,
    preferredLayouts: ["center-chest", "micro-chest", "symbol-above-type"],
    preferredSymbols: ["interrupted-arc", "frame", "minimal-star"],
    preferredOrnaments: ["rule-lines", "roman-ids", "tiny-capsules"],
    allowedEffects: ["outline", "filled", "washed"],
    visualRhythm: 1.05,
    trackingWide: 0.52,
    headlineScale: 1.05,
    geometryScale: 0.88,
    strokeHairline: 0.3,
  }),
  "silent-luxury": defineStyle("silent-luxury", "Silent Luxury", {
    typographyPreference: ["luxury-serif", "condensed"],
    spacing: { ...BASE.spacing, elementGap: 18 },
    negativeSpace: 0.44,
    preferredLayouts: ["center-chest", "micro-chest", "floating-composition"],
    preferredSymbols: ["interrupted-arc", "halo", "missing-center-void"],
    preferredOrnaments: ["micro-dots", "roman-ids", "alignment-guides"],
    preferredPrintScale: "micro",
    hierarchy: "geometry-first",
    allowedEffects: ["outline", "filled", "fade"],
    visualRhythm: 0.92,
    trackingWide: 0.44,
    headlineScale: 0.92,
    geometryScale: 0.65,
    strokeHairline: 0.25,
    strokeThin: 0.45,
  }),
  "editorial-fashion": defineStyle("editorial-fashion", "Editorial Fashion", {
    typographyPreference: ["editorial-serif", "extended"],
    spacing: { ...BASE.spacing, elementGap: 14 },
    negativeSpace: 0.3,
    preferredLayouts: ["editorial-layout", "oversized-front", "oversized-back"],
    preferredSymbols: ["frame", "architectural-line"],
    preferredOrnaments: ["editorial-dividers", "rule-lines", "collection-numbers"],
    preferredPrintScale: "oversized",
    hierarchy: "type-first",
    allowedEffects: ["outline", "filled", "halftone"],
    visualRhythm: 1.18,
    trackingWide: 0.58,
    headlineScale: 1.15,
    geometryScale: 0.72,
    alignment: "optical",
    strokeThin: 0.5,
  }),
  architectural: defineStyle("architectural", "Architectural", {
    typographyPreference: ["grotesk", "modern-sans"],
    spacing: { ...BASE.spacing, elementGap: 10 },
    negativeSpace: 0.22,
    preferredLayouts: ["center-chest", "split-layout", "gallery-layout"],
    preferredSymbols: ["frame", "grid", "architectural-line"],
    preferredOrnaments: ["alignment-guides", "corner-marks", "luxury-borders"],
    allowedEffects: ["outline", "outline-fill", "heavy-ink"],
    visualRhythm: 1.08,
    trackingNormal: 0.22,
    geometryScale: 1.12,
    strokeRegular: 0.85,
  }),
  faith: defineStyle("faith", "Faith", {
    typographyPreference: ["luxury-serif", "editorial-serif"],
    spacing: { ...BASE.spacing, elementGap: 14 },
    negativeSpace: 0.32,
    preferredLayouts: ["center-chest", "vertical-print", "symbol-above-type"],
    preferredSymbols: ["cross", "sacred-geometry", "halo"],
    preferredOrnaments: ["roman-ids", "rule-lines", "minimal-labels"],
    hierarchy: "geometry-first",
    allowedEffects: ["outline", "filled", "embroidery"],
    trackingWide: 0.42,
    geometryScale: 0.95,
    strokeThin: 0.55,
  }),
  "vintage-washed": defineStyle("vintage-washed", "Vintage Washed", {
    typographyPreference: ["grotesk", "condensed"],
    spacing: { ...BASE.spacing, elementGap: 12 },
    negativeSpace: 0.26,
    preferredLayouts: ["oversized-front", "gallery-layout", "wrap-composition"],
    preferredSymbols: ["broken-circle", "split-circle", "orbit"],
    preferredOrnaments: ["collection-numbers", "coordinates", "micro-dots"],
    preferredPrintScale: "oversized",
    hierarchy: "type-first",
    allowedEffects: ["vintage-distress", "washed", "screen-print-noise", "fade"],
    visualRhythm: 1.12,
    trackingNormal: 0.32,
    geometryScale: 0.9,
    strokeThin: 0.7,
  }),
  "modern-gothic": defineStyle("modern-gothic", "Modern Gothic", {
    typographyPreference: ["condensed", "extended"],
    spacing: { ...BASE.spacing, elementGap: 10 },
    negativeSpace: 0.2,
    preferredLayouts: ["center-chest", "vertical-print", "diagonal-layout"],
    preferredSymbols: ["broken-circle", "cross", "minimal-star"],
    preferredOrnaments: ["rule-lines", "corner-marks", "roman-ids"],
    allowedEffects: ["outline", "heavy-ink", "texture-mask"],
    visualRhythm: 0.95,
    trackingTight: 0.08,
    trackingWide: 0.35,
    headlineScale: 1.1,
    geometryScale: 1.05,
    strokeRegular: 1.2,
  }),
  "japanese-minimal": defineStyle("japanese-minimal", "Japanese Minimal", {
    typographyPreference: ["modern-sans", "grotesk"],
    spacing: { ...BASE.spacing, elementGap: 20, baselineGrid: 4 },
    negativeSpace: 0.46,
    preferredLayouts: ["center-chest", "micro-chest", "floating-composition"],
    preferredSymbols: ["halo", "half-circle", "minimal-eye"],
    preferredOrnaments: ["micro-dots", "alignment-guides", "rule-lines"],
    preferredPrintScale: "micro",
    hierarchy: "geometry-first",
    allowedEffects: ["outline", "filled", "fade"],
    visualRhythm: 0.88,
    trackingWide: 0.55,
    headlineScale: 0.88,
    geometryScale: 0.6,
    alignment: "optical",
    strokeHairline: 0.28,
  }),
  "technical-streetwear": defineStyle("technical-streetwear", "Technical Streetwear", {
    typographyPreference: ["grotesk", "condensed"],
    spacing: { ...BASE.spacing, elementGap: 8 },
    negativeSpace: 0.18,
    preferredLayouts: ["vertical-print", "split-layout", "dual-print"],
    preferredSymbols: ["grid", "compass", "directional-marker"],
    preferredOrnaments: ["coordinates", "registration-marks", "alignment-guides"],
    allowedEffects: ["outline", "screen-print-noise", "halftone", "heavy-ink"],
    visualRhythm: 1.05,
    trackingTight: 0.15,
    trackingNormal: 0.24,
    geometryScale: 1.15,
    alignment: "left",
    strokeThin: 0.55,
  }),
  "swiss-typography": defineStyle("swiss-typography", "Swiss Typography", {
    typographyPreference: ["grotesk", "modern-sans"],
    spacing: { ...BASE.spacing, elementGap: 8, baselineGrid: 4 },
    negativeSpace: 0.3,
    preferredLayouts: ["editorial-layout", "split-layout", "gallery-layout"],
    preferredSymbols: ["grid", "architectural-line", "frame"],
    preferredOrnaments: ["rule-lines", "alignment-guides", "editorial-dividers"],
    preferredPrintScale: "oversized",
    hierarchy: "type-first",
    allowedEffects: ["outline", "filled", "halftone"],
    visualRhythm: 1.15,
    trackingTight: 0.06,
    trackingNormal: 0.14,
    headlineScale: 1.18,
    geometryScale: 0.55,
    alignment: "optical",
    strokeHairline: 0.4,
  }),
  "scandinavian-minimal": defineStyle("scandinavian-minimal", "Scandinavian Minimal", {
    typographyPreference: ["modern-sans", "extended"],
    spacing: { ...BASE.spacing, elementGap: 18 },
    negativeSpace: 0.4,
    preferredLayouts: ["center-chest", "floating-composition", "micro-chest"],
    preferredSymbols: ["half-circle", "halo", "minimal-star"],
    preferredOrnaments: ["micro-dots", "rule-lines", "minimal-labels"],
    allowedEffects: ["outline", "filled", "washed"],
    visualRhythm: 0.96,
    trackingWide: 0.5,
    headlineScale: 0.95,
    geometryScale: 0.7,
    strokeHairline: 0.32,
  }),
  "monochrome-luxury": defineStyle("monochrome-luxury", "Monochrome Luxury", {
    typographyPreference: ["luxury-serif", "condensed"],
    spacing: { ...BASE.spacing, elementGap: 16 },
    negativeSpace: 0.42,
    preferredLayouts: ["center-chest", "symbol-above-type", "micro-chest"],
    preferredSymbols: ["interrupted-arc", "frame", "diamond"],
    preferredOrnaments: ["luxury-borders", "roman-ids", "tiny-capsules"],
    preferredPrintScale: "micro",
    hierarchy: "geometry-first",
    allowedEffects: ["outline", "filled", "fade"],
    visualRhythm: 0.94,
    trackingWide: 0.46,
    headlineScale: 0.9,
    geometryScale: 0.62,
    strokeHairline: 0.28,
    strokeThin: 0.48,
  }),
};

export const ALL_STYLE_IDS = Object.keys(STYLE_REGISTRY) as DesignStyleId[];

export function getStyle(id: DesignStyleId): DesignStyleDefinition {
  return STYLE_REGISTRY[id] ?? STYLE_REGISTRY["minimal-luxury"];
}
