import type { LayoutSystemKnowledge } from "../../types";

export const LAYOUT_SYSTEMS: LayoutSystemKnowledge[] = [
  {
    id: "spine-layout",
    title: "Spine Layout",
    principle: "Vertical axis dominance along garment spine — editorial, architectural, sacred geometry.",
    whenToUse: "Back prints with vertical hero type, faith/architect collections, statement spines.",
    whenNotToUse: "Front chest, wide horizontal slogans, figurative center graphics.",
    signals: ["spine", "vertical-axis", "rotated-type"],
    antiPatterns: ["horizontal-poster", "centered-logo-front"],
    placementRules: ["Anchor on center back vertical axis", "Offset from collar 55–70mm", "Hero may rotate -90° along spine"],
    spacingRules: ["60%+ negative space flanking axis", "Micro labels horizontal at spine intersection only"],
    visualBalance: "Symmetric void, asymmetric type weight — optical center not mathematical center.",
    recommendedGarments: ["oversized-tee", "hoodie", "long-sleeve"],
    commercialUseCase: "Capsule hero backs, editorial drops, identity pieces.",
    negativeSpaceTarget: "65%",
  },
  {
    id: "editorial-layout",
    title: "Editorial Layout",
    principle: "Fashion-magazine composition — type breaks frames, overlaps graphics, asymmetric focal points.",
    whenToUse: "Campaign backs, gallery drops, luxury editorial streetwear.",
    whenNotToUse: "POD fast graphics, logo-only chest marks, technical schematics.",
    signals: ["editorial", "type-first", "asymmetric-focal"],
    antiPatterns: ["symmetric-logo", "wireframe-stack"],
    placementRules: ["Focal at upper-third back", "Secondary at lower editorial band", "Graphics frame type — never trap it"],
    spacingRules: ["Irregular editorial gaps", "Hero tracking wide", "Micro at optical margin"],
    visualBalance: "Asymmetric with controlled tension — one heavy quadrant, three quiet.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Instagram back-shots, lookbook hero pieces.",
    negativeSpaceTarget: "55%",
  },
  {
    id: "oversized-center",
    title: "Oversized Center",
    principle: "Monumental centered statement — hero dominates 40–50% of print zone.",
    whenToUse: "Statement word backs, season launches, scroll-stop pieces.",
    whenNotToUse: "Multi-line stories, dense graphic surrounds, chest prints.",
    signals: ["oversized-center", "statement-hero", "monumental"],
    antiPatterns: ["small-centered-logo", "crowded-perimeter"],
    placementRules: ["Center back, upper-mid zone", "Hero vertically centered in print bbox", "Perimeter graphics at 70% scale of hero"],
    spacingRules: ["Minimum 25% void above hero", "Secondary 45% below hero size"],
    visualBalance: "Heavy center with perimeter whisper — not filled frame.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Viral back prints, festival drops, identity statements.",
    negativeSpaceTarget: "50%",
  },
  {
    id: "corner-composition",
    title: "Corner Composition",
    principle: "Focal weight in one quadrant — creates dynamic tension and premium asymmetry.",
    whenToUse: "Left chest, sleeve accents, asymmetric front marks.",
    whenNotToUse: "Centered back statements, symmetric badge layouts.",
    signals: ["corner-anchor", "asymmetric", "quadrant-weight"],
    antiPatterns: ["dead-center", "four-corner-clutter"],
    placementRules: ["Anchor upper-left or lower-right chest", "Offset from collar and side seam", "Opposite corner stays empty"],
    spacingRules: ["Void in opposing quadrant", "Micro label at anchor corner only"],
    visualBalance: "One weighted corner, three open — optical pull toward anchor.",
    recommendedGarments: ["oversized-tee", "crewneck", "hoodie"],
    commercialUseCase: "Daily rotation marks, subtle luxury, layering-friendly.",
    negativeSpaceTarget: "70%",
  },
  {
    id: "luxury-badge",
    title: "Luxury Badge",
    principle: "Contained emblem frame — heritage label psychology without copying any house.",
    whenToUse: "Front chest, center back medallions, capsule seals.",
    whenNotToUse: "Full-back oversized statements, distressed rave graphics.",
    signals: ["badge-frame", "heritage-label", "contained-emblem"],
    antiPatterns: ["unframed-chaos", "fake-wax-seal-cliché"],
    placementRules: ["Center of badge zone", "Frame 55% of print area", "Hero inside frame, micro below"],
    spacingRules: ["Frame stroke 0.8–1.4mm", "Internal padding 15% of frame"],
    visualBalance: "Symmetrical frame, asymmetric internal hierarchy.",
    recommendedGarments: ["oversized-tee", "hoodie", "crewneck"],
    commercialUseCase: "Premium everyday wear, giftable pieces, brand seals.",
    negativeSpaceTarget: "60%",
  },
  {
    id: "bottom-label",
    title: "Bottom Label",
    principle: "Gravity-settled metadata band — whispers production story at hem zone.",
    whenToUse: "Back prints with top-heavy heroes, museum labels, collection metadata.",
    whenNotToUse: "Chest prints, spine layouts, oversized center statements.",
    signals: ["bottom-band", "hem-label", "metadata-strip"],
    antiPatterns: ["label-at-top", "full-width-bar"],
    placementRules: ["Lower third of print area", "Max 20% print height", "Center or left-aligned in band"],
    spacingRules: ["12mm+ clear from hero", "Micro type only in band"],
    visualBalance: "Top-heavy void, bottom whisper — inverted pyramid.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Collection numbering, capsule IDs, editorial credits.",
    negativeSpaceTarget: "58%",
  },
  {
    id: "top-heavy",
    title: "Top Heavy",
    principle: "Visual weight concentrated upper back — reads in mirror and back-shot photography.",
    whenToUse: "Upper back prints, hoodie placements, photo-forward drops.",
    whenNotToUse: "Hem-zone only graphics, bottom-label-only layouts.",
    signals: ["upper-back", "top-weight", "mirror-read"],
    antiPatterns: ["bottom-heavy", "centered-poster-symmetry"],
    placementRules: ["Offset from collar 50–65mm", "Focal in upper 40% of bbox", "Lower zone reserved for void or micro"],
    spacingRules: ["Collar clearance 50mm+", "Descending size hierarchy top to bottom"],
    visualBalance: "Heavy top, light bottom — garment drape compensated.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Social content backs, influencer flat-lays.",
    negativeSpaceTarget: "55%",
  },
  {
    id: "diagonal-composition",
    title: "Diagonal Composition",
    principle: "Dynamic diagonal axis creates movement — premium streetwear energy without chaos.",
    whenToUse: "Abstract geometry layouts, campaign graphics, energetic capsules.",
    whenNotToUse: "Silent collection, museum label, minimal chest marks.",
    signals: ["diagonal", "dynamic-axis", "movement"],
    antiPatterns: ["static-center", "grid-locked"],
    placementRules: ["45° implied axis through focal", "Type may follow diagonal", "Graphics echo axis direction"],
    spacingRules: ["Counter-diagonal void for balance", "No competing diagonals"],
    visualBalance: "Dynamic tension resolved by negative space on opposing diagonal.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Limited drops, energetic youth capsules.",
    negativeSpaceTarget: "52%",
  },
  {
    id: "negative-space-layout",
    title: "Negative Space Layout",
    principle: "The void is the design — focal occupies less than 35% of print area.",
    whenToUse: "Silent collection, luxury minimal, daily rotation prestige.",
    whenNotToUse: "Scroll-stop campaign backs needing immediate impact.",
    signals: ["void-dominant", "sparse", "silent-luxury"],
    antiPatterns: ["filled-frame", "every-corner-occupied"],
    placementRules: ["Single focal at optical center or offset", "Nothing in outer 30% margin ring"],
    spacingRules: ["Minimum 65% void", "One hero, zero or one micro"],
    visualBalance: "Extreme restraint — confidence through emptiness.",
    recommendedGarments: ["oversized-tee", "crewneck", "hoodie"],
    commercialUseCase: "Premium pricing, wardrobe staples, quiet luxury.",
    negativeSpaceTarget: "70%",
  },
  {
    id: "split-composition",
    title: "Split Composition",
    principle: "Dual-zone layout — type zone and graphic zone with clear editorial separation.",
    whenToUse: "Type + symbol stories, dual-message backs, editorial splits.",
    whenNotToUse: "Single-word statements, minimal emblems.",
    signals: ["split", "dual-zone", "type-graphic-separation"],
    antiPatterns: ["merged-zones", "competing-focals"],
    placementRules: ["Horizontal or vertical split at 40/60 ratio", "One zone type, one zone graphic", "Divider line optional"],
    spacingRules: ["Clear gutter between zones", "No bleed across split without intention"],
    visualBalance: "Weighted split — not 50/50 unless silent symmetry intended.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Storytelling pieces, faith/architect narratives.",
    negativeSpaceTarget: "50%",
  },
  {
    id: "grid-composition",
    title: "Grid Composition",
    principle: "Technical editorial grid — thin lines, registration marks, blueprint discipline.",
    whenToUse: "Technical luxury, architect collection, production-forward aesthetics.",
    whenNotToUse: "Organic faith curves, distressed vintage, soft editorial.",
    signals: ["grid", "technical", "blueprint"],
    antiPatterns: ["organic-only", "no-structure"],
    placementRules: ["Grid aligned to print margins", "Focal at grid intersection", "Marks at corners only"],
    spacingRules: ["Grid opacity below 40%", "Type breaks grid intentionally"],
    visualBalance: "Rigid structure with one intentional break for fashion tension.",
    recommendedGarments: ["oversized-tee", "hoodie"],
    commercialUseCase: "Architect drops, technical capsule, design-literate buyers.",
    negativeSpaceTarget: "55%",
  },
  {
    id: "floating-composition",
    title: "Floating Composition",
    principle: "Elements float in void — no frame, no perimeter trap, pure garment-scale presence.",
    whenToUse: "Minimal luxury, ghost type, single symbol floats.",
    whenNotToUse: "Badge layouts, perimeter-heavy designs, vintage label frames.",
    signals: ["floating", "unframed", "void-surround"],
    antiPatterns: ["heavy-frame", "boxed-in"],
    placementRules: ["Focal at optical center with offset option", "No enclosing rectangle", "Graphics orbit at distance"],
    spacingRules: ["Minimum 50% void on all sides of focal", "Micro floats independently"],
    visualBalance: "Isolated focal with orbital micro-elements.",
    recommendedGarments: ["oversized-tee", "crewneck", "hoodie"],
    commercialUseCase: "Premium basics, elevated essentials.",
    negativeSpaceTarget: "65%",
  },
];

export function getLayoutSystem(id: LayoutSystemKnowledge["id"]): LayoutSystemKnowledge {
  const entry = LAYOUT_SYSTEMS.find((s) => s.id === id);
  if (!entry) throw new Error(`Unknown layout system: ${id}`);
  return entry;
}
