import type { TypographyKnowledge } from "../../types";

export const TYPOGRAPHY_KNOWLEDGE: TypographyKnowledge[] = [
  {
    id: "hierarchy",
    title: "Typography Hierarchy",
    principle: "One dominant voice, one supporting layer, optional micro whisper. Never equal-weight blocks.",
    whenToUse: "Every garment print — hero must read at 3m, micro at 30cm.",
    whenNotToUse: "Never flatten hierarchy for 'balance' — that creates merch-label density.",
    signals: ["hero-secondary-micro", "scale-contrast", "weight-distribution"],
    antiPatterns: ["equal-size-blocks", "logo-caption-stack", "three-heroes"],
    luxuryWeight: 0.95,
    garmentScaleNotes: "Hero 8–16mm on oversized back; micro 3–5mm max.",
  },
  {
    id: "spacing",
    title: "Premium Spacing",
    principle: "Luxury lives in air. Vertical rhythm must feel editorial, not grid-locked.",
    whenToUse: "Stacked headlines, badge layouts, spine typography.",
    whenNotToUse: "Tight poster packing — kills premium perception on garment.",
    signals: ["breathing-room", "editorial-gaps", "asymmetric-rhythm"],
    antiPatterns: ["uniform-gaps", "centered-caption-spacing", "crowded-stack"],
    luxuryWeight: 0.92,
    garmentScaleNotes: "Minimum 4mm between hero and secondary on chest prints.",
  },
  {
    id: "tracking",
    title: "Editorial Tracking",
    principle: "Wide tracking signals fashion editorial; tight tracking signals sports merch.",
    whenToUse: "Uppercase hero lines, luxury badges, silent collection marks.",
    whenNotToUse: "Body copy lengths, lowercase sentences, micro legal text.",
    signals: ["wide-tracked", "uppercase-hero", "letterspace-luxury"],
    antiPatterns: ["tight-tracking", "default-kerning-only", "condensed-merch"],
    luxuryWeight: 0.9,
    garmentScaleNotes: "+250 to +500 tracking equivalent on hero at garment scale.",
  },
  {
    id: "kerning",
    title: "Optical Kerning",
    principle: "Pair-adjust AV, WA, LT, RY — optical balance over mathematical centering.",
    whenToUse: "Short hero words, brand tokens, editorial headlines.",
    whenNotToUse: "Long paragraphs or distressed type where edge fade dominates.",
    signals: ["optical-pairs", "headline-refinement"],
    antiPatterns: ["no-pair-adjustment", "font-default-only"],
    luxuryWeight: 0.78,
    garmentScaleNotes: "Critical at 10mm+ hero sizes where letterforms dominate.",
  },
  {
    id: "oversized-typography",
    title: "Oversized Typography",
    principle: "Monumental type as artwork — cropped, bleeding, or spine-dominant.",
    whenToUse: "Back prints, statement pieces, capsule drops with single word heroes.",
    whenNotToUse: "Left chest, sleeve, or multi-line storytelling layouts.",
    signals: ["overscale", "crop-bleed", "statement-type"],
    antiPatterns: ["small-safe-type", "poster-scale-on-chest"],
    luxuryWeight: 0.93,
    garmentScaleNotes: "Fill 40–60% of print area height — never 90% (poster look).",
  },
  {
    id: "editorial-typography",
    title: "Editorial Typography",
    principle: "Type breaks frames, overlaps graphics, creates tension with negative space.",
    whenToUse: "Gallery editorial, luxury back prints, fashion campaign layouts.",
    whenNotToUse: "Technical blueprint or minimal emblem marks.",
    signals: ["type-over-graphic", "frame-break", "editorial-serif-sans-mix"],
    antiPatterns: ["type-below-symbol", "passive-caption"],
    luxuryWeight: 0.91,
    garmentScaleNotes: "Serif hero + sans micro is proven luxury streetwear pairing.",
  },
  {
    id: "luxury-typography",
    title: "Luxury Typography",
    principle: "Restraint, precision, and whispered metadata — never loud label density.",
    whenToUse: "Milaene DNA, silent collection, museum label systems.",
    whenNotToUse: "Hype drops, meme text, promotional slogans.",
    signals: ["whispered-micro", "roman-numerals", "capsule-ids"],
    antiPatterns: ["slogan-stacking", "price-callouts", "fake-latin"],
    luxuryWeight: 0.96,
    garmentScaleNotes: "Maximum 3 visible text blocks at garment viewing distance.",
  },
  {
    id: "minimal-typography",
    title: "Minimal Typography",
    principle: "One word or mark carries the entire identity — silence is the design.",
    whenToUse: "Left chest, micro branding, daily rotation pieces.",
    whenNotToUse: "Campaign hero backs needing scroll-stop impact.",
    signals: ["single-word", "micro-mark", "quiet-confidence"],
    antiPatterns: ["secondary-noise", "explanation-text"],
    luxuryWeight: 0.88,
    garmentScaleNotes: "6–8mm hero max on chest — reads as intentional, not timid.",
  },
  {
    id: "print-typography",
    title: "Print Typography",
    principle: "Vector-only type with ink-safe weights — no hairlines, no image text.",
    whenToUse: "All production artwork — plastisol, DTG, screen print.",
    whenNotToUse: "Never rasterize type or use AI-generated letterforms.",
    signals: ["vector-text", "ink-safe-stroke", "flat-plastisol"],
    antiPatterns: ["image-text", "hairline-serif", "gradient-type"],
    luxuryWeight: 0.85,
    garmentScaleNotes: "Minimum 0.5mm effective stroke at production scale.",
  },
];

export function getTypographyKnowledge(id: TypographyKnowledge["id"]): TypographyKnowledge {
  const entry = TYPOGRAPHY_KNOWLEDGE.find((k) => k.id === id);
  if (!entry) throw new Error(`Unknown typography knowledge: ${id}`);
  return entry;
}
