import type { TypographyRecipe } from "@/lib/design/design-knowledge/typography-language/types";
import { expandArchetype, lerp } from "@/lib/design/design-knowledge/shared/variant";

const FIT = ["oversized-front", "oversized-back", "center-chest"] as const;

function typoBase(partial: Omit<TypographyRecipe, "id" | "meta">): Omit<TypographyRecipe, "id" | "meta"> {
  return partial;
}

const ARCHETYPES: Parameters<typeof expandArchetype<TypographyRecipe>>[0][] = [
  { archetype: "Luxury Serif", base: typoBase({ family: "luxury-serif", headlineWeight: 500, subheadWeight: 400, decorWeight: 400, headlineScale: 1.15, subheadScale: 0.42, decorScale: 0.22, trackingTight: 0.02, trackingWide: 0.38, lineHeight: 1.05, alignment: "middle", interaction: "overlaps-symbol", layerPriority: 90, roles: ["headline", "subheadline", "roman-numeral"], editorialSpacing: 1.12 }), variantCount: 16, name: () => "Luxury Serif", tags: ["serif", "luxury"], collections: ["editorial", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, trackingWide: lerp(s, v, 0.32, 0.48), headlineScale: lerp(s, v + 1, 1.05, 1.28) }) },
  { archetype: "Modern Grotesk", base: typoBase({ family: "modern-grotesk", headlineWeight: 500, subheadWeight: 450, decorWeight: 400, headlineScale: 1.08, subheadScale: 0.38, decorScale: 0.2, trackingTight: 0.04, trackingWide: 0.28, lineHeight: 1.02, alignment: "start", interaction: "breaks-frame", layerPriority: 88, roles: ["headline", "stacked-headline", "collection-code"], editorialSpacing: 1.05 }), variantCount: 16, name: () => "Modern Grotesk", tags: ["grotesk", "sans"], collections: ["capsule", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, alignment: v % 3 === 0 ? "broken" : "start" }) },
  { archetype: "Editorial Sans", base: typoBase({ family: "editorial-sans", headlineWeight: 450, subheadWeight: 400, decorWeight: 400, headlineScale: 1.22, subheadScale: 0.45, decorScale: 0.24, trackingTight: 0.06, trackingWide: 0.42, lineHeight: 1.08, alignment: "middle", interaction: "through-geometry", layerPriority: 92, roles: ["stacked-headline", "headline", "subheadline"], editorialSpacing: 1.18 }), variantCount: 16, name: () => "Editorial Sans", tags: ["editorial", "sans"], collections: ["editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, headlineScale: lerp(s, v, 1.1, 1.35) }) },
  { archetype: "Fashion Condensed", base: typoBase({ family: "fashion-condensed", headlineWeight: 500, subheadWeight: 450, decorWeight: 400, headlineScale: 1.35, subheadScale: 0.35, decorScale: 0.18, trackingTight: 0.08, trackingWide: 0.22, lineHeight: 0.98, alignment: "start", interaction: "overlaps-symbol", layerPriority: 91, roles: ["headline", "vertical-text"], editorialSpacing: 0.95 }), variantCount: 16, name: () => "Fashion Condensed", tags: ["condensed", "fashion"], collections: ["season", "campaign"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, trackingTight: lerp(s, v, 0.06, 0.14) }) },
  { archetype: "Museum Label", base: typoBase({ family: "museum-label", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.85, subheadScale: 0.32, decorScale: 0.16, trackingTight: 0.1, trackingWide: 0.35, lineHeight: 1.15, alignment: "start", interaction: "floats-independent", layerPriority: 75, roles: ["micro-label", "caption", "collection-code"], editorialSpacing: 1.25 }), variantCount: 16, name: () => "Museum Label", tags: ["museum", "label"], collections: ["museum", "silent"], garmentFit: ["center-chest"], mutate: (b, v, s) => ({ ...b, decorScale: lerp(s, v, 0.12, 0.2) }) },
  { archetype: "Roman Numeral", base: typoBase({ family: "roman-numeral", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.28, subheadScale: 0.22, decorScale: 0.18, trackingTight: 0.2, trackingWide: 0.45, lineHeight: 1.1, alignment: "start", interaction: "anchors-edge", layerPriority: 40, roles: ["roman-numeral"], editorialSpacing: 1.3 }), variantCount: 16, name: () => "Roman Numeral", tags: ["roman", "index"], collections: ["museum", "architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, trackingWide: lerp(s, v, 0.38, 0.55) }) },
  { archetype: "Coordinates", base: typoBase({ family: "coordinates", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.24, subheadScale: 0.2, decorScale: 0.16, trackingTight: 0.15, trackingWide: 0.32, lineHeight: 1.05, alignment: "start", interaction: "anchors-edge", layerPriority: 35, roles: ["coordinates"], editorialSpacing: 1.2 }), variantCount: 16, name: () => "Coordinates", tags: ["coordinates", "geo"], collections: ["architect", "faith"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, decorScale: lerp(s, v, 0.14, 0.22) }) },
  { archetype: "Capsule ID", base: typoBase({ family: "capsule-id", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.32, subheadScale: 0.26, decorScale: 0.2, trackingTight: 0.12, trackingWide: 0.4, lineHeight: 1.08, alignment: "middle", interaction: "floats-independent", layerPriority: 45, roles: ["collection-code", "micro-label"], editorialSpacing: 1.15 }), variantCount: 16, name: () => "Capsule ID", tags: ["capsule", "id"], collections: ["capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, trackingWide: lerp(s, v, 0.35, 0.5) }) },
  { archetype: "Collection Name", base: typoBase({ family: "collection-name", headlineWeight: 500, subheadWeight: 400, decorWeight: 400, headlineScale: 1.05, subheadScale: 0.4, decorScale: 0.22, trackingTight: 0.05, trackingWide: 0.36, lineHeight: 1.06, alignment: "middle", interaction: "overlaps-symbol", layerPriority: 85, roles: ["headline", "subheadline"], editorialSpacing: 1.1 }), variantCount: 16, name: () => "Collection Name", tags: ["collection", "season"], collections: ["season", "editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, headlineScale: lerp(s, v, 0.95, 1.18) }) },
  { archetype: "Production ID", base: typoBase({ family: "production-id", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.26, subheadScale: 0.22, decorScale: 0.18, trackingTight: 0.14, trackingWide: 0.38, lineHeight: 1.05, alignment: "start", interaction: "anchors-edge", layerPriority: 30, roles: ["micro-label", "caption"], editorialSpacing: 1.18 }), variantCount: 16, name: () => "Production ID", tags: ["production", "stamp"], collections: ["capsule", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, decorScale: lerp(s, v, 0.15, 0.24) }) },
  { archetype: "Garment ID", base: typoBase({ family: "garment-id", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.3, subheadScale: 0.24, decorScale: 0.19, trackingTight: 0.1, trackingWide: 0.42, lineHeight: 1.1, alignment: "end", interaction: "anchors-edge", layerPriority: 32, roles: ["micro-label"], editorialSpacing: 1.22 }), variantCount: 16, name: () => "Garment ID", tags: ["garment", "tag"], collections: ["season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, alignment: v % 2 === 0 ? "end" : "start" }) },
  { archetype: "Broken Typography", base: typoBase({ family: "broken-type", headlineWeight: 500, subheadWeight: 450, decorWeight: 400, headlineScale: 1.12, subheadScale: 0.48, decorScale: 0.22, trackingTight: 0.04, trackingWide: 0.34, lineHeight: 1.04, alignment: "broken", interaction: "breaks-frame", layerPriority: 87, roles: ["stacked-headline", "headline"], editorialSpacing: 1.08 }), variantCount: 16, name: () => "Broken Typography", tags: ["broken", "offset"], collections: ["editorial", "capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, interaction: "breaks-frame", alignment: "broken" }) },
  { archetype: "Vertical Typography", base: typoBase({ family: "vertical-type", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.95, subheadScale: 0.35, decorScale: 0.2, trackingTight: 0.18, trackingWide: 0.28, lineHeight: 1.2, alignment: "start", interaction: "floats-independent", layerPriority: 70, roles: ["vertical-text", "headline"], editorialSpacing: 1.35 }), variantCount: 16, name: () => "Vertical Typography", tags: ["vertical", "rail"], collections: ["faith", "architect"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, trackingTight: lerp(s, v, 0.14, 0.24) }) },
  { archetype: "Oversized Typography", base: typoBase({ family: "oversized-type", headlineWeight: 500, subheadWeight: 450, decorWeight: 400, headlineScale: 1.42, subheadScale: 0.38, decorScale: 0.2, trackingTight: 0.02, trackingWide: 0.3, lineHeight: 0.96, alignment: "start", interaction: "overlaps-symbol", layerPriority: 95, roles: ["headline", "stacked-headline"], editorialSpacing: 0.92 }), variantCount: 16, name: () => "Oversized Typography", tags: ["oversized", "bold"], collections: ["editorial", "season"], garmentFit: ["oversized-front", "oversized-back"], mutate: (b, v, s) => ({ ...b, headlineScale: lerp(s, v, 1.28, 1.55) }) },
  { archetype: "Split Typography", base: typoBase({ family: "split-type", headlineWeight: 500, subheadWeight: 450, decorWeight: 400, headlineScale: 1.1, subheadScale: 0.72, decorScale: 0.22, trackingTight: 0.05, trackingWide: 0.32, lineHeight: 1.02, alignment: "start", interaction: "through-geometry", layerPriority: 89, roles: ["stacked-headline", "headline"], editorialSpacing: 1.05 }), variantCount: 16, name: () => "Split Typography", tags: ["split", "dual"], collections: ["editorial", "capsule"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, subheadScale: lerp(s, v, 0.62, 0.82) }) },
  { archetype: "Offset Typography", base: typoBase({ family: "offset-type", headlineWeight: 450, subheadWeight: 400, decorWeight: 400, headlineScale: 1.02, subheadScale: 0.4, decorScale: 0.2, trackingTight: 0.06, trackingWide: 0.36, lineHeight: 1.06, alignment: "start", interaction: "floats-independent", layerPriority: 82, roles: ["headline", "subheadline"], editorialSpacing: 1.12 }), variantCount: 16, name: () => "Offset Typography", tags: ["offset", "asymmetric"], collections: ["silent", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, interaction: "floats-independent" }) },
  { archetype: "Ghost Typography", base: typoBase({ family: "ghost-type", headlineWeight: 400, subheadWeight: 400, decorWeight: 400, headlineScale: 0.18, subheadScale: 0.14, decorScale: 0.12, trackingTight: 0.22, trackingWide: 0.48, lineHeight: 1.1, alignment: "middle", interaction: "behind-geometry", layerPriority: 25, roles: ["headline"], editorialSpacing: 1.4 }), variantCount: 16, name: () => "Ghost Typography", tags: ["ghost", "depth"], collections: ["editorial", "silent"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, headlineScale: lerp(s, v, 0.14, 0.22), interaction: "behind-geometry" }) },
  { archetype: "Multi Scale Typography", base: typoBase({ family: "multi-scale", headlineWeight: 500, subheadWeight: 400, decorWeight: 400, headlineScale: 1.35, subheadScale: 0.35, decorScale: 0.14, trackingTight: 0.04, trackingWide: 0.4, lineHeight: 1.04, alignment: "broken", interaction: "overlaps-symbol", layerPriority: 93, roles: ["headline", "stacked-headline", "micro-label", "roman-numeral"], editorialSpacing: 1.15 }), variantCount: 16, name: () => "Multi Scale", tags: ["multi-scale", "hierarchy"], collections: ["editorial", "season"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, decorScale: lerp(s, v, 0.1, 0.18), headlineScale: lerp(s, v + 1, 1.2, 1.45) }) },
  { archetype: "Editorial Spacing", base: typoBase({ family: "editorial-sans", headlineWeight: 450, subheadWeight: 400, decorWeight: 400, headlineScale: 1.08, subheadScale: 0.42, decorScale: 0.2, trackingTight: 0.08, trackingWide: 0.44, lineHeight: 1.12, alignment: "middle", interaction: "through-geometry", layerPriority: 86, roles: ["headline", "subheadline", "caption"], editorialSpacing: 1.28 }), variantCount: 16, name: () => "Editorial Spacing", tags: ["spacing", "tracking"], collections: ["editorial"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, editorialSpacing: lerp(s, v, 1.15, 1.38), trackingWide: lerp(s, v + 1, 0.38, 0.52) }) },
  { archetype: "Hierarchy System", base: typoBase({ family: "luxury-serif", headlineWeight: 500, subheadWeight: 450, decorWeight: 400, headlineScale: 1.2, subheadScale: 0.45, decorScale: 0.2, trackingTight: 0.04, trackingWide: 0.36, lineHeight: 1.06, alignment: "middle", interaction: "overlaps-symbol", layerPriority: 94, roles: ["stacked-headline", "headline", "subheadline", "roman-numeral", "collection-code"], editorialSpacing: 1.1 }), variantCount: 16, name: () => "Hierarchy System", tags: ["hierarchy", "system"], collections: ["editorial", "museum"], garmentFit: [...FIT], mutate: (b, v, s) => ({ ...b, layerPriority: Math.round(lerp(s, v, 88, 96)) }) },
];

export const TYPOGRAPHY_ARCHETYPE_COUNT = ARCHETYPES.length;
export const TYPOGRAPHY_VARIANTS_PER_ARCHETYPE = 16;
export const TYPOGRAPHY_RECIPE_TARGET = TYPOGRAPHY_ARCHETYPE_COUNT * TYPOGRAPHY_VARIANTS_PER_ARCHETYPE;

export function buildAllTypographyRecipes(seed = 0): TypographyRecipe[] {
  return ARCHETYPES.flatMap((a) => expandArchetype<TypographyRecipe>(a, seed));
}
