import type { ResearchCreativeBrief } from "./types";

/**
 * Formats the creative brief as a plain design strategy document.
 * No image prompts, artwork instructions, or generative model directives.
 */
export function formatCreativeBriefDocument(brief: ResearchCreativeBrief): string {
  return [
    `Concept Name: ${brief.conceptName}`,
    "",
    "Executive Summary",
    brief.executiveSummary,
    "",
    "Business Case",
    brief.businessCase,
    "",
    `Trend Score: ${brief.scores.trendScore}`,
    `Brand Fit: ${brief.scores.brandFit}`,
    `Commercial Potential: ${brief.scores.commercialPotential}`,
    `Competition: ${brief.scores.competition}`,
    `Longevity: ${brief.scores.longevity}`,
    `Originality: ${brief.scores.originality}`,
    "",
    "Target Audience",
    brief.targetAudience.join("\n"),
    "",
    `Recommended Product: ${brief.recommendedProduct}`,
    "Alternative Products",
    brief.alternativeProducts.join("\n"),
    "",
    "Recommended Placement",
    brief.recommendedPlacement.join("\n"),
    "",
    "Typography Direction",
    brief.typographyDirection.join("\n"),
    "",
    "Graphic Direction",
    brief.graphicDirection.join("\n"),
    "",
    "Color Palette",
    brief.colorPalette.join("\n"),
    "",
    "Material Recommendation",
    brief.materialRecommendation.join("\n"),
    "",
    "Print Technique",
    brief.printTechnique.join("\n"),
    "",
    "Production Notes",
    brief.productionNotes,
    "",
    "Avoid",
    brief.avoid.join("\n"),
    "",
    "Research Evidence",
    brief.researchEvidence.join("\n"),
    "",
    `Next Step: ${brief.nextStep}`,
  ].join("\n");
}
