import type { WorkspaceScope } from "@/lib/persona/domain/types";
import type { DeterministicAssetRepository, RecordDeterministicAsset } from "@/lib/image/deterministic-runtime/asset-repository";
import type { DeterministicReviewRequest } from "@/lib/image/deterministic-runtime/review-types";
import type { DeterministicAsset } from "@/lib/image/deterministic-runtime/types";
export class MemoryDeterministicAssetRepository implements DeterministicAssetRepository{
  assets:DeterministicAsset[]=[];
  async record(scope:WorkspaceScope,input:RecordDeterministicAsset){const existing=await this.getByJob(scope,input.job.id);if(existing)return existing;const now=input.generatedAt;const asset:DeterministicAsset={id:input.id,workspaceId:scope.workspaceId,productionProjectId:input.job.productionProjectId,generationJobId:input.job.id,shotId:input.job.inputSnapshot.shot.assetId,inputFingerprint:input.job.inputFingerprint,storagePath:input.storagePath,baseStageOutputId:input.baseStageOutputId,compositeStageOutputId:input.compositeStageOutputId,reviewStatus:"REVIEW_REQUIRED",mockupReview:{contractVersion:"mockup-human-review-v1",overallStatus:"REVIEW_REQUIRED",identity:"NEEDS_REVIEW",productFidelity:"NEEDS_REVIEW",artworkFidelityExact:"NEEDS_REVIEW",placement:"NEEDS_REVIEW",perspective:"NEEDS_REVIEW",lightingIntegration:"NEEDS_REVIEW",reviewedBy:null,reviewedAt:null,note:null},reviewedBy:null,reviewedAt:null,reviewNote:null,generatedAt:now,createdAt:now,updatedAt:now};this.assets.push(asset);return structuredClone(asset);}
  async getByJob(scope:WorkspaceScope,jobId:string){return structuredClone(this.assets.find((asset)=>asset.workspaceId===scope.workspaceId&&asset.generationJobId===jobId)??null);}
  async getByJobs(scope:WorkspaceScope,jobIds:readonly string[]){const ids=new Set(jobIds);return new Map(this.assets.filter((asset)=>asset.workspaceId===scope.workspaceId&&ids.has(asset.generationJobId)).map((asset)=>[asset.generationJobId,structuredClone(asset)]));}
  async review(scope:WorkspaceScope&{actorId:string},assetId:string,input:DeterministicReviewRequest,now:string){const index=this.assets.findIndex((asset)=>asset.workspaceId===scope.workspaceId&&asset.id===assetId);if(index<0)throw new Error("Asset not found");const current=this.assets[index]!;const next:DeterministicAsset={...current,reviewStatus:input.decision,reviewedBy:scope.actorId,reviewedAt:now,reviewNote:input.note,updatedAt:now,mockupReview:{contractVersion:"mockup-human-review-v1",overallStatus:input.decision,...input.checklist,reviewedBy:scope.actorId,reviewedAt:now,note:input.note}};this.assets[index]=next;return structuredClone(next);}
}
