import { createAdminClient } from "@/lib/supabase/admin";
import { PersonaDomainError, PersonaStoreError } from "@/lib/persona/domain/errors";
import type { WorkspaceScope } from "@/lib/persona/domain/types";
import { normalizeOptionalRfc3339Timestamp, normalizeRfc3339Timestamp } from "@/lib/datetime/rfc3339";
import type { DeterministicAssetRepository, RecordDeterministicAsset } from "@/lib/image/deterministic-runtime/asset-repository";
import type { DeterministicReviewRequest } from "@/lib/image/deterministic-runtime/review-types";
import { deterministicAssetSchema, type DeterministicAsset } from "@/lib/image/deterministic-runtime/types";

function map(row: Record<string, unknown>): DeterministicAsset {
  return deterministicAssetSchema.parse({ id:row.id,workspaceId:row.workspace_id,productionProjectId:row.production_project_id,generationJobId:row.generation_job_id,shotId:row.shot_id,inputFingerprint:row.input_fingerprint,storagePath:row.storage_path,baseStageOutputId:row.base_stage_output_id,compositeStageOutputId:row.composite_stage_output_id,reviewStatus:row.review_status,mockupReview:row.mockup_review,reviewedBy:row.reviewed_by,reviewedAt:normalizeOptionalRfc3339Timestamp(row.reviewed_at),reviewNote:row.review_note,generatedAt:normalizeRfc3339Timestamp(row.generated_at),createdAt:normalizeRfc3339Timestamp(row.created_at),updatedAt:normalizeRfc3339Timestamp(row.updated_at) });
}

export class SupabaseDeterministicAssetRepository implements DeterministicAssetRepository {
  async record(scope:WorkspaceScope,input:RecordDeterministicAsset){
    if(input.job.workspaceId!==scope.workspaceId)throw new PersonaDomainError("Job belongs to another workspace.","UNAUTHORIZED_WORKSPACE");
    const s=input.job.inputSnapshot; const now=input.generatedAt;
    const provenance={attemptId:input.compositeStageOutputId,provider:s.baseGeneration.provider,model:s.baseGeneration.model,providerRequestId:input.baseProviderRequestId,identityStrategy:null,identity:null,paidGeneration:{jobId:input.job.id,productionProjectId:input.job.productionProjectId,productionProjectVersion:input.job.productionProjectVersion,inputFingerprint:input.job.inputFingerprint,masterArtwork:{artworkId:s.masterArtwork.artworkId,designId:s.masterArtwork.designId,version:s.masterArtwork.version,checksum:s.masterArtwork.checksum},product:input.productContext,shotId:s.shot.assetId},startedAt:input.job.startedAt??now,completedAt:now};
    const mockupReview={contractVersion:"mockup-human-review-v1",overallStatus:"REVIEW_REQUIRED",identity:"NEEDS_REVIEW",productFidelity:"NEEDS_REVIEW",artworkFidelityExact:"NEEDS_REVIEW",placement:"NEEDS_REVIEW",perspective:"NEEDS_REVIEW",lightingIntegration:"NEEDS_REVIEW",reviewedBy:null,reviewedAt:null,note:null};
    const {data,error}=await createAdminClient().from("image_production_assets").insert({id:input.id,workspace_id:scope.workspaceId,production_project_id:input.job.productionProjectId,generation_job_id:input.job.id,shot_id:s.shot.assetId,input_fingerprint:input.job.inputFingerprint,brand_model:s.brandModel,master_artwork:{id:s.masterArtwork.artworkId,designId:s.masterArtwork.designId,version:s.masterArtwork.version,checksum:s.masterArtwork.checksum},product_context:input.productContext,provider:s.baseGeneration.provider,model:s.baseGeneration.model,provider_request_id:input.baseProviderRequestId,storage_path:input.storagePath,provenance,review_status:"REVIEW_REQUIRED",mockup_review:mockupReview,base_stage_output_id:input.baseStageOutputId,composite_stage_output_id:input.compositeStageOutputId,generated_at:now,created_at:now,updated_at:now}).select("*").single();
    if(error||!data){const replay=await this.getByJob(scope,input.job.id);if(replay)return replay;throw new PersonaStoreError(error?.message??"Failed to persist deterministic final asset.");}
    await createAdminClient().from("image_production_projects").update({status:"REVIEW",updated_at:now}).eq("workspace_id",scope.workspaceId).eq("id",input.job.productionProjectId);
    return map(data as Record<string,unknown>);
  }
  async getByJob(scope:WorkspaceScope,jobId:string){const {data,error}=await createAdminClient().from("image_production_assets").select("*").eq("workspace_id",scope.workspaceId).eq("generation_job_id",jobId).not("composite_stage_output_id","is",null).maybeSingle();if(error)throw new PersonaStoreError(error.message);return data?map(data as Record<string,unknown>):null;}
  async review(scope:WorkspaceScope&{actorId:string},assetId:string,input:DeterministicReviewRequest,now:string){const overall=input.decision;const review={contractVersion:"mockup-human-review-v1",overallStatus:overall,identity:input.checklist.identity,productFidelity:input.checklist.productFidelity,artworkFidelityExact:input.checklist.artworkFidelityExact,placement:input.checklist.placement,perspective:input.checklist.perspective,lightingIntegration:input.checklist.lightingIntegration,reviewedBy:scope.actorId,reviewedAt:now,note:input.note};const {data,error}=await createAdminClient().from("image_production_assets").update({review_status:overall,mockup_review:review,reviewed_by:scope.actorId,reviewed_at:now,review_note:input.note,updated_at:now}).eq("workspace_id",scope.workspaceId).eq("id",assetId).not("composite_stage_output_id","is",null).select("*").maybeSingle();if(error||!data)throw new PersonaDomainError(error?.message??"Deterministic asset not found.","NOT_FOUND");return map(data as Record<string,unknown>);}
}
