import type { FashionPsychologyPrinciple } from "../../types";

export const FASHION_PSYCHOLOGY: FashionPsychologyPrinciple[] = [
  {
    id: "premium-perception",
    title: "Premium Perception",
    principle: "Buyers judge premium in the first 200ms — negative space, tracking, and restraint signal price tier.",
    whenToUse: "Every Milaene piece targeting €55+ positioning.",
    whenNotToUse: "Never sacrifice premium signals for scroll-stop gimmicks.",
    emotionalLever: "Worthiness — 'this brand respects my taste'",
    designApplication: "60%+ void, wide tracking, max 3 text blocks, no poster density.",
    signals: ["void", "restraint", "tracking"],
    antiPatterns: ["crowded", "cheap-poster", "merch-label"],
  },
  {
    id: "luxury-feeling",
    title: "Luxury Feeling",
    principle: "Luxury is calm confidence — not loud logos, not maximal graphics.",
    whenToUse: "Silent collection, museum label, negative space layouts.",
    whenNotToUse: "Festival drops, meme culture, hype graphics.",
    emotionalLever: "Aspiration without desperation",
    designApplication: "Whispered micro labels, serif/sans pairing, single focal symbol.",
    signals: ["calm", "whisper", "editorial"],
    antiPatterns: ["loud", "maximal", "logo-shout"],
  },
  {
    id: "identity",
    title: "Identity",
    principle: "Wearers buy identity projection — the garment says who they are.",
    whenToUse: "Faith, architect, silent identity capsules.",
    whenNotToUse: "Generic trend graphics with no narrative.",
    emotionalLever: "Belonging to a taste tribe",
    designApplication: "Collection language consistency, symbolic meaning, not random text.",
    signals: ["tribe", "meaning", "collection-dna"],
    antiPatterns: ["generic", "trend-chase", "no-story"],
  },
  {
    id: "belonging",
    title: "Belonging",
    principle: "Capsule drops create in-group recognition without exclusionary hype.",
    whenToUse: "Numbered capsules, season codes, MILAENE brand moments.",
    whenNotToUse: "Insider gatekeeping aesthetics, counterfeit vibes.",
    emotionalLever: "Recognized by those who know",
    designApplication: "Subtle capsule IDs, collection metadata, brand token discipline.",
    signals: ["capsule", "recognition", "insider"],
    antiPatterns: ["fake-scarcity", "hype-gate"],
  },
  {
    id: "status",
    title: "Status",
    principle: "Quiet status beats loud status in premium streetwear — understatement signals taste.",
    whenToUse: "Left chest marks, micro branding, daily rotation pieces.",
    whenNotToUse: "Giant logo backs competing with luxury houses.",
    emotionalLever: "Taste signaling over wealth signaling",
    designApplication: "Small precise marks, premium materials implied through design restraint.",
    signals: ["understated", "precise", "taste"],
    antiPatterns: ["loud-logo", "flex-culture"],
  },
  {
    id: "minimalism",
    title: "Minimalism",
    principle: "Reduction is the ultimate luxury craft — every removed element must earn its absence.",
    whenToUse: "Silent collection, floating composition, minimal typography.",
    whenNotToUse: "Campaign backs needing immediate scroll-stop impact.",
    emotionalLever: "Confidence through reduction",
    designApplication: "One hero, optional one micro, 70% void.",
    signals: ["reduction", "single-focal", "void"],
    antiPatterns: ["decoration", "fill-every-corner"],
  },
  {
    id: "emotional-storytelling",
    title: "Emotional Storytelling",
    principle: "Abstract narrative through geometry and type — never literal illustration.",
    whenToUse: "Faith, architect, emotional capsule drops.",
    whenNotToUse: "Figurative animals, faces, narrative comics on garment.",
    emotionalLever: "Felt meaning without explained meaning",
    designApplication: "Symbol language, spine layouts, split compositions.",
    signals: ["abstract-narrative", "symbol", "emotion"],
    antiPatterns: ["literal-illustration", "comic-panel"],
  },
  {
    id: "color-psychology",
    title: "Color Psychology",
    principle: "Monochrome and near-monochrome signal luxury — off-white on black, concrete grey accents.",
    whenToUse: "Milaene default palette — minimal ink count.",
    whenNotToUse: "Neon bursts, rainbow gradients, multi-color hype.",
    emotionalLever: "Sophistication through restraint",
    designApplication: "1–2 ink colors, off-white #ECEAE4, concrete #8A8A8A.",
    signals: ["monochrome", "off-white", "concrete"],
    antiPatterns: ["neon", "gradient", "rainbow"],
  },
  {
    id: "visual-tension",
    title: "Visual Tension",
    principle: "Controlled tension between type and void creates fashion interest — chaos kills premium.",
    whenToUse: "Editorial layouts, diagonal composition, split zones.",
    whenNotToUse: "Silent minimal, floating marks, negative space layouts.",
    emotionalLever: "Engaged eye without fatigue",
    designApplication: "Asymmetric focal, type-frame breaks, one tension axis.",
    signals: ["tension", "asymmetric", "break-frame"],
    antiPatterns: ["chaos", "uniform-tension-everywhere"],
  },
];

export function getFashionPsychology(id: string): FashionPsychologyPrinciple | undefined {
  return FASHION_PSYCHOLOGY.find((p) => p.id === id);
}
