/**
 * Optional Milaene Brand Cast creation presets — templates only, never auto-submit.
 */

import type { CreationProjectPreset } from "../domain/creation-types";

export const PERSONA_CREATION_PRESETS: CreationProjectPreset[] = [
  {
    id: "milaene_street_luxury",
    label: "Milaene Street Luxury",
    brand_role: "primary_male",
    gender_presentation: "Male",
    age_range: "25-32",
    height_range: "178-187 cm",
    body_type: "Lean athletic, natural everyday proportions",
    skin_tone_direction: "Warm light-medium olive / Mediterranean, lightly sun-kissed",
    face_shape_direction: "Defined approachable jaw, friendly modern masculine features",
    hair_direction: "Dark brown to near-black textured crop / messy crop / natural fade",
    facial_hair_direction: "Light natural stubble",
    eye_direction: "Warm friendly eyes, relaxed calm gaze",
    expression_direction: "Relaxed confidence, authentic ease, never arrogant or aggressive",
    personality: "Modern, sympathisch, authentic urban lifestyle presence",
    fashion_style: "Premium streetwear lifestyle",
    visual_keywords:
      "premium streetwear, urban lifestyle, authentic, community, Instagram followable, Milan Barcelona Copenhagen street",
    excluded_features:
      "fashion week, runway, Vogue, magazine cover, CEO portrait, corporate headshot, aggressive face, angry eyes, overstyled hair, glossy beauty skin, turtleneck, blazer, suit, flashy jewelry, cartoonish features, orange fake tan, bodybuilder",
    preferred_brand_looks: "Milaene Premium Streetwear Lifestyle",
    preferred_outfits:
      "Heavyweight oversized tee, heavyweight hoodie, zip hoodie, sweatpants-friendly tonal streetwear basics — no logos",
    intended_usage: "image_and_video",
    candidate_count: 4,
  },
  {
    id: "primary_male_quiet_luxury",
    label: "Primary Male / Everyday Premium",
    brand_role: "primary_male",
    gender_presentation: "Male",
    age_range: "26-33",
    height_range: "178-186 cm",
    body_type: "Lean athletic everyday",
    skin_tone_direction: "Warm light-medium olive",
    face_shape_direction: "Approachable defined jaw, natural features",
    hair_direction: "Dark textured short crop, relaxed",
    facial_hair_direction: "Light stubble",
    eye_direction: "Warm brown or hazel, friendly",
    expression_direction: "Calm authentic confidence",
    personality: "Reserved warmth, real lifestyle presence",
    fashion_style: "Everyday premium streetwear",
    visual_keywords: "authentic, premium casual, urban lifestyle, community",
    excluded_features: "fashion week, CEO look, glossy beauty skin, flashy jewelry, cartoonish features",
    preferred_brand_looks: "Everyday Premium",
    preferred_outfits: "Heavyweight black tee, tonal hoodie basics",
    intended_usage: "image_and_video",
    candidate_count: 4,
  },
  {
    id: "secondary_male_street_editorial",
    label: "Secondary Male / Urban Creator",
    brand_role: "secondary_male",
    gender_presentation: "Male",
    age_range: "24-31",
    height_range: "175-185 cm",
    body_type: "Lean casual athletic",
    skin_tone_direction: "Warm medium olive",
    face_shape_direction: "Distinctive but approachable",
    hair_direction: "Messy crop or natural fade",
    facial_hair_direction: "Light casual stubble",
    eye_direction: "Dark brown, open and friendly",
    expression_direction: "Cool relaxed creator energy",
    personality: "Understated cool, community-friendly",
    fashion_style: "Urban creator streetwear lifestyle",
    visual_keywords: "creator, urban, authentic, Instagram lifestyle",
    excluded_features: "runway pose, logos, neon, aggressive face, corporate look",
    preferred_brand_looks: "Urban Creator",
    preferred_outfits: "Heavyweight hoodie, oversized tee, tonal streetwear",
    intended_usage: "image_and_video",
    candidate_count: 4,
  },
  {
    id: "primary_female_minimal_editorial",
    label: "Primary Female / Minimal Editorial",
    brand_role: "primary_female",
    gender_presentation: "Female",
    age_range: "25-32",
    height_range: "170-178 cm",
    body_type: "Athletic lean",
    skin_tone_direction: "Light olive to medium",
    face_shape_direction: "Soft jawline, balanced features",
    hair_direction: "Dark brown straight or soft wave",
    facial_hair_direction: "None",
    eye_direction: "Hazel or brown",
    expression_direction: "Calm, authentic lifestyle ease",
    personality: "Quiet presence, approachable",
    fashion_style: "Minimal premium lifestyle",
    visual_keywords: "clean, refined, lifestyle, brand-forward",
    excluded_features: "heavy glam, plastic look, over-retouching, fashion-week drama",
    preferred_brand_looks: "Minimal Lifestyle",
    preferred_outfits: "Premium basics, soft structure neutrals",
    intended_usage: "image_and_video",
    candidate_count: 4,
  },
];

export function getCreationPreset(id: string): CreationProjectPreset | null {
  return PERSONA_CREATION_PRESETS.find((p) => p.id === id) ?? null;
}
